-- NOT REQUIRED: production inspected on 2026-09-06 already has
-- exceptions_run_id_code_key on (run_id, code), which supports run lookups.
-- No additional index is created. Investigate the authenticated query plan
-- before adding another index; preserve RLS and all historical audit data.
