import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const app = readFileSync(join(root, "app.js"), "utf8");
const formats = readFileSync(join(root, "formats.js"), "utf8");
const html = readFileSync(join(root, "index.html"), "utf8");
const sb = readFileSync(join(root, "supabase.js"), "utf8");
const accessSql = readFileSync(join(root, "supabase/20260830_user_roles_company_access.sql"), "utf8");
const adminSql = readFileSync(join(root, "supabase/20260830_admin_full_access.sql"), "utf8");
const checklistSql = readFileSync(join(root, "supabase/20260831_registry_driven_daily_checklist.sql"), "utf8");
const boFirstSql = readFileSync(join(root, "supabase/20260831_bo_first_daily_coverage.sql"), "utf8");
const operatingStartSql = readFileSync(join(root, "supabase/20260831_operational_start_20260830.sql"), "utf8");
const inviteFn = readFileSync(join(root, "supabase/functions/admin-invite-user/index.ts"), "utf8");

assert.match(app, /const DEFAULT_RANGE_FROM[\s\S]+d - 30/, "ค่าเริ่มต้นต้องครอบคลุมย้อนหลัง 30 วัน");
assert.match(app, /const OPERATING_START_DATE = "2026-08-30"/, "รอบใช้งานจริงต้องเริ่มวันที่ 30 สิงหาคม 2026");
assert.match(app, /candidate < OPERATING_START_DATE \? OPERATING_START_DATE : candidate/, "ช่วงข้อมูลเริ่มต้นต้องไม่ย้อนก่อนวันเริ่มใช้งานจริง");
assert.match(operatingStartSql, /operational_start_date[\s\S]+date '2026-08-30'/, "ฐานข้อมูลต้องเริ่มรอบใช้งานจริงวันที่ 30 สิงหาคม 2026");
assert.match(operatingStartSql, /business_date < date '2026-08-30'[\s\S]+is_archived/, "งานก่อนวันที่ 30 ต้องถูกเก็บเป็นประวัติ");
assert.match(app, /resultMetric\(exceptionsAvailable, sorted\.length\)[\s\S]+รายการรอตรวจ/, "การ์ดรายการรอตรวจต้องตรงกับรายการที่กรองแล้ว");
assert.match(app, /ขยายย้อนหลัง 90 วัน/, "หน้าไม่มีข้อมูลต้องแนะนำให้ขยายช่วงวัน");
assert.match(html, /หน้านี้ใช้ข้อมูลจริงจาก Supabase/, "หน้า login ต้องอธิบายสาเหตุที่ต้องเข้าสู่ระบบ");
assert.doesNotMatch(html, /gmail\.js/, "หน้าเว็บต้องไม่โหลดตัวอ่าน Gmail ที่เลิกใช้แล้ว");
assert.equal(existsSync(join(root, "gmail.js")), false, "ต้องลบ gmail.js ที่ไม่ได้ใช้แล้ว");
assert.equal(existsSync(join(root, "fx.js")), false, "ต้องลบ fx.js placeholder ที่ไม่ได้ใช้แล้ว");
assert.match(app, /const core = await Promise\.allSettled/, "ตัวโหลดภาพรวมต้องยอมให้ข้อมูลบางส่วนสำเร็จได้");
assert.match(app, /ตัวเลขส่วนนี้จะแสดง “—” แทนศูนย์/, "หน้าเว็บต้องไม่แสดงศูนย์ปลอมเมื่อข้อมูลจริง timeout");
assert.match(app, /const cloudQueryKey = \(\) =>/, "คลังไฟล์ต้องสร้าง cache key ตามตัวกรอง");
assert.match(app, /requestId !== cloudState\.requestId \|\| key !== cloudQueryKey\(\)/, "ผลค้นหาเก่าต้องเขียนทับตัวกรองใหม่ไม่ได้");
assert.match(app, /retryTransientFileRequest\(action, attempts = 3\)/, "Preview ต้องลองใหม่เมื่อ Storage หรือฐานข้อมูล timeout");
assert.match(app, /const exceptionsAvailable = liveOverviewState\.exceptionsReady/, "หน้า Exception ต้องแยกข้อมูลไม่พร้อมออกจากศูนย์จริง");
assert.match(app, /const operationsAvailable = Array\.isArray\(liveOverviewState\.operations\)/, "หน้ารายงานต้องแยกคิวไม่พร้อมออกจากไม่มีข้อมูล");
assert.match(app, /const logsAvailable = liveOverviewState\.logsReady/, "Audit Log ต้องไม่แสดงศูนย์เมื่อ query ล้มเหลว");
assert.match(app, /LIVE_COMPANY_CODES/, "ต้องแยก 9 บริษัทจริงออกจากแถวรวมชื่อระบบ");
assert.match(app, /\.filter\(isLiveCompanyRow\)/, "ผลคิวและผลกระทบยอดต้องกรองแถว PM\/SYS123\/XXX ออก");
assert.match(app, /ภาพรวมการกระทบยอด 3 จุด/, "หน้ารายวันต้องสรุป STM\/PM เทียบ BO ในจุดเดียว");
assert.match(app, /ขั้นถัดไปที่แนะนำ/, "หน้ารายวันต้องบอกงานถัดไปที่ผู้ตรวจควรทำ");
assert.match(app, /date === PROD_TODAY && !selectedQuality\.some/, "หน้ารายวันต้องเลื่อนไปวันที่ล่าสุดที่มีผลจริงเมื่อวันนี้ยังไม่มีผลรัน");
assert.match(app, /Audit Sheet · ภาพรวมทุกบริษัท/, "หน้ารายวันต้องมีตารางภาพรวมแบบสเปรดชีต");
assert.match(app, /data-sheet-mode="\$\{row\.missing\.length/, "แต่ละบริษัทต้องมีปุ่มไปแก้ไฟล์ ตรวจข้อผิดปกติ หรืออนุมัติ");
assert.match(app, /data-case-open=/, "ตาราง Exception ต้องมีปุ่มตรวจเคสที่เห็นชัด");
assert.match(app, /data-case-files=/, "ตาราง Exception ต้องมีปุ่มเปิดไฟล์ประกอบโดยตรง");
assert.match(app, /class="case-file-row"/, "ไฟล์ประกอบในเคสต้องแสดงเป็นรายการที่กด Preview ได้ทั้งแถว");
assert.ok(app.includes('data-file-status="${file.parse_error ? "error" : file.parsed ? "parsed" : "waiting"}"`'), "attribute สถานะไฟล์ต้องปิด quote ครบเพื่อไม่ให้ DOM ของรายการไฟล์เสีย");
assert.match(app, /Sb\.exceptionFiles\(e\.runId, e\.clarificationFileId\)/, "Drawer ต้องโหลดไฟล์ที่ใช้สร้าง recon run เฉพาะตอนเปิดเคส");
assert.match(app, /ไฟล์ประกอบของเคสนี้/, "Drawer ต้องมีส่วนไฟล์ประกอบที่เข้าใจง่าย");
assert.match(app, /ยอดตรงกัน หรือบันทึกความเสียหายแล้ว/, "เงื่อนไขปิดเคสต้องไม่วนกลับจนอนุมัติไม่ได้");
assert.match(app, /กำลังโหลดข้อมูลจริง…/, "หน้า Exception ต้องบอกผู้ใช้ชัดเจนระหว่างโหลดข้อมูลจริง");
assert.match(app, /recon-kpi-grid/, "สรุปผลกระทบยอดต้องใช้การ์ดหลักขนาดสม่ำเสมอ");
assert.match(app, /function safeExceptionDetail\(e\)/, "เคสย้อนหลังที่วันที่เสียต้องไม่แสดง undefined หรือ NaN ต่อผู้ใช้");
assert.doesNotMatch(app, /id: "pm", label: "PM Monitor"/, "เมนู PM Monitor ที่ซ้ำซ้อนต้องถูกถอดออก");
assert.doesNotMatch(app, /VIEWS\.pm\s*=/, "route PM Monitor เดิมต้องไม่ค้างอยู่ในแอป");
assert.doesNotMatch(app, /function renderLivePm/, "ตัว render PM Monitor เดิมต้องไม่ค้างอยู่ใน bundle");
assert.match(app, /async function loadLiveDamage\(force = false\)/, "ทะเบียนความเสียหายต้องโหลดข้อมูลจริงแยกจาก query ภาพรวม");
assert.match(app, /ยังไม่มีความเสียหายที่ยืนยันแล้วในช่วงนี้/, "ทะเบียนความเสียหายต้องอธิบายสถานะว่างโดยไม่แสดงศูนย์ให้เข้าใจผิด");
assert.match(app, /await Sb\.post\("damages"[\s\S]+await loadLiveDamage\(true\)/, "บันทึกความเสียหายต้องรอ Supabase สำเร็จและรีเฟรชทะเบียนทันที");
assert.match(app, /บันทึก Supabase ไม่สำเร็จ:[\s\S]+DB\.damages = DB\.damages\.filter/, "หากบันทึกจริงล้มเหลวต้องย้อนสถานะ optimistic ออก");
assert.match(app, /เคสใหม่ ยังไม่ได้ส่งชี้แจง/, "หน้าชี้แจงต้องแยกเคสใหม่ออกจากเคสที่ส่งให้ทีมแล้ว");
assert.match(app, /data-clarify-company=/, "การ์ดบริษัทในหน้าชี้แจงต้องกดเปิดรายการเคสได้");
assert.match(app, /ตรวจคำชี้แจงที่ตอบแล้ว/, "ปุ่มคิวอนุมัติต้องบอกชัดว่าเป็นคำชี้แจงที่ทีมตอบแล้ว");
assert.match(app, /id: "users", label: "ผู้ใช้และสิทธิ์"/, "ผู้ดูแลระบบต้องมีหน้าจัดการผู้ใช้จริง");
assert.match(app, /admin: Object\.keys\(ROUTE_MAP\)/, "ผู้ดูแลระบบต้องเข้าถึงทุก route");
assert.match(app, /!it\.hidden \|\| state\.role === "admin"/, "ผู้ดูแลระบบต้องเห็นหน้าวิเคราะห์ที่ซ่อนจากบทบาททั่วไป");
assert.match(app, /id="newAccessUser">\+ เพิ่มผู้ใช้/, "หน้าระบบต้องเพิ่มผู้ใช้ใหม่ได้โดยตรง");
assert.match(app, /Sb\.adminInviteUser\(/, "ผู้ใช้ใหม่ต้องถูกเชิญผ่าน Edge Function ที่ปลอดภัย");
assert.match(app, /async function applyAuthenticatedRole\(\)[\s\S]+await Sb\.myAccess\(\)/, "บทบาทต้องอ่านจาก Supabase ไม่ใช่ metadata ฝั่ง browser");
assert.doesNotMatch(app, /user\.user_metadata\?\.role/, "ห้ามเชื่อ role จาก user_metadata");
assert.match(app, /function enterProductionApp|async function enterProductionApp/, "ต้องมีทางเข้าระบบหลังตรวจสิทธิ์");
assert.match(app, /canAccessCompany\(e\.company\)/, "รายการ Exception ต้องกรองตามบริษัทที่รับผิดชอบ");
assert.match(sb, /const myAccess = \(\) => rpc\("get_my_access"\)/, "client ต้องอ่านสิทธิ์จริงผ่าน RPC");
assert.match(sb, /\/functions\/v1\/admin-invite-user/, "client ต้องเรียก Edge Function สำหรับเชิญผู้ใช้");
assert.match(accessSql, /create table if not exists public\.app_profiles/, "migration ต้องมีทะเบียนโปรไฟล์ผู้ใช้");
assert.match(accessSql, /create table if not exists public\.user_company_access/, "migration ต้องมีขอบเขตบริษัทต่อผู้ใช้");
assert.match(accessSql, /drop policy if exists mail_batches_auth_read|t\|\|'_auth_read'/, "migration ต้องยกเลิก policy อ่านได้ทุกบริษัทเดิม");
assert.match(accessSql, /public\.has_company_access\(company\)/, "RLS ต้องตรวจบริษัทของผู้ใช้");
assert.match(adminSql, /'monitor','lead','shift_lead','admin'/, "RLS ต้องอนุญาต admin ช่วยอัปเดต workflow");
assert.match(inviteFn, /SUPABASE_SERVICE_ROLE_KEY/, "การเชิญผู้ใช้ต้องใช้ service role เฉพาะฝั่ง Edge Function");
assert.match(inviteFn, /caller\.role !== "admin"/, "Edge Function ต้องตรวจบทบาทผู้เรียกซ้ำฝั่ง server");
assert.match(inviteFn, /inviteUserByEmail/, "Edge Function ต้องส่งอีเมลเชิญจริง");
assert.doesNotMatch(app + sb, /SUPABASE_SERVICE_ROLE_KEY/, "frontend ห้ามอ้าง service role key");
assert.match(app, /05:00–08:00[\s\S]+รับไฟล์ตรวจจากแอดมิน/, "Dashboard ต้องแสดงช่วงรับไฟล์ประจำวัน");
assert.match(app, /ระบบอ่าน BO ก่อนเพื่อรู้บัญชี\/Provider ที่ใช้จริง แล้วจึงตรวจ STM\/PM ที่ต้องส่ง/, "Checklist ต้องอธิบายลำดับ BO-first");
assert.match(app, /Sb\.boFirstCoverage/, "Dashboard ต้องโหลดผล BO-first จากฐานข้อมูล");
assert.match(app, /สรุปเอกสาร BO ที่ตรวจ/, "สรุปรายวันต้องมีส่วนสรุปเอกสาร BO ที่ตรวจ");
assert.match(app, /<th>ระบบ<\/th><th>บริษัท<\/th><th>บัญชี \/ Provider<\/th>/, "สรุป BO-first ต้องแสดงระบบและบริษัทก่อนบัญชี Provider");
assert.match(app, /<th>ชื่อเต็มจาก BO<\/th>/, "สรุป BO-first ต้องแสดงชื่อเต็มต้นฉบับเพื่อรีเช็ก");
assert.match(app, /businessSystemOfCompany/, "BO-first ต้องแยกระบบตามบริษัทเพื่อไม่จับคู่ข้ามระบบ");
assert.match(app, /มีไฟล์แล้ว · ไม่พบเลขบัญชีคู่/, "เมื่อมี STM แล้ว หน้าจอต้องไม่สรุปผิดว่าไม่มีไฟล์");
assert.match(app, /ไฟล์ STM\/PM ที่ได้รับและอ่านแล้ว แต่ยังจับกับ BO ไม่ได้/, "หน้าจอต้องแจกแจงไฟล์ที่รับแล้วแต่จับ BO ไม่ได้");
assert.match(app, /data-bo-follow=/, "แต่ละกลุ่ม BO-first ต้องเปิดรายละเอียดติดตามได้");
assert.match(app, /ข้อความพร้อมส่งให้ทีม/, "รายละเอียดติดตามต้องมีข้อความที่คัดลอกส่งทีมได้");
assert.match(app, /1\. ข้อมูลรายการที่อ่านจาก BO/, "ข้อความติดตามต้องบอกชัดว่าข้อมูลอ้างอิงอ่านจาก BO");
assert.match(app, /4\. สิ่งที่ขอให้ทีมตรวจ/, "ข้อความติดตามต้องแยกสิ่งที่ทีมต้องดำเนินการให้เห็นชัด");
assert.match(app, /ไฟล์ที่ระบบได้รับและใช้ตรวจ/, "ส่วนไฟล์ต้องอธิบายว่าเป็นไฟล์ที่ระบบได้รับและใช้ตรวจ");
assert.match(app, /numberedFileText/, "ข้อความคัดลอกต้องไล่ลำดับชื่อไฟล์ทีละรายการ");
assert.match(app, /รวม \$\{num\(totalRelatedFiles\)\} ไฟล์/, "หน้าติดตามต้องแสดงจำนวนไฟล์ที่เกี่ยวข้องรวม");
assert.match(app, /data-bo-preview/, "ไฟล์ที่เกี่ยวข้องต้องเปิด Preview จริงจากรายละเอียดได้");
assert.match(app, /เปิดหน้าติดตามเคส/, "ผู้ตรวจต้องดำเนินการต่อจากรายละเอียด BO-first ได้");
assert.match(app, /บัญชี\/Provider ที่ BO ระบุ/, "สรุป BO ต้องแสดงบัญชีหรือ Provider ที่พบจาก BO");
assert.match(app, /STM ตาม BO/, "Checklist ต้องแสดง STM ตามบัญชีที่ BO ระบุ");
assert.match(boFirstSql, /summary->'bo_first'->'required'/, "view ต้องเปิดรายการที่ BO กำหนดให้หน้าเว็บใช้");
assert.match(app, /expectedBoCount\(row\)/, "Checklist ต้องใช้ BO 1 หรือ 2 ไฟล์ตามระบบบริษัท");
assert.match(app, /ทะเบียน: \$\{h\(row\.registry_warning\)\}/, "คำเตือนทะเบียนต้องแยกจากรายการไฟล์ที่ขาด");
assert.match(checklistSql, /create table if not exists public\.audit_company_file_rules/, "migration ต้องมี master rule จากทะเบียนบัญชี");
assert.match(checklistSql, /\('FR8','123',2,6,9/, "บริษัทระบบ 123 ต้องคาดหวัง BO ฝากและถอนแยก 2 ไฟล์");
assert.match(checklistSql, /\('UFABET7M','7M',1,6,8/, "บริษัท 7M ต้องคาดหวัง BO รวมฝากถอน 1 ไฟล์");
assert.match(checklistSql, /f\.kind='bo_main'/, "BO ต้องนับจากชนิดไฟล์จริง ไม่ใช่คำ BO ในหัวข้อเมล");
assert.doesNotMatch(checklistSql, /case when coalesce\(stm_count,0\)=0/, "STM ต้องไม่ถูกแจ้งขาดเพียงเพราะบัญชีไม่ได้ใช้งานวันนั้น");
assert.doesNotMatch(checklistSql, /case when coalesce\(pm_deposit_count,0\)=0/, "PM ต้องไม่ถูกแจ้งขาดเพียงเพราะ Provider ไม่ได้ใช้งานวันนั้น");
assert.match(checklistSql, /local_time<time '08:00' then 'receiving'/, "ระบบต้องรอจนจบช่วงรับไฟล์ก่อนแจ้งขาด");
assert.match(checklistSql, /array\['AUTOPEER','AZPAY','12PAY','MYPAY','COREPAY'\]/, "ทะเบียนระบบ XXX ต้องสะท้อน Provider ที่ยังเปิดใช้งานในชีตล่าสุด");
assert.match(checklistSql, /array\['AUTOPEER','AZPAY','CYBERPLUS','MYPAY','COREPAY'\]/, "ทะเบียนระบบ 123 ต้องสะท้อน Provider ในชีตล่าสุดและเตือน CPXM แยกต่างหาก");
assert.match(app + formats, /COREPAY/, "ตัวอ่านชื่อไฟล์ต้องรู้จัก COREPAY หรือ CP PAY");
assert.match(app + formats, /CPXM/, "ตัวอ่านชื่อไฟล์ต้องรู้จัก CPXM");
assert.match(app, /หลัง 19:00[\s\S]+ติดตามทีมออดิท/, "หน้าระบบต้องบอกขั้นตอนติดตามทีมออดิทหลังเวลาอัปโหลด");

console.log("App shell QA follow-up: 85 checks passed");
