import assert from "node:assert/strict";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const app = readFileSync(join(root, "app.js"), "utf8");
const html = readFileSync(join(root, "index.html"), "utf8");

assert.match(app, /const DEFAULT_RANGE_FROM[\s\S]+d - 30/, "ค่าเริ่มต้นต้องครอบคลุมย้อนหลัง 30 วัน");
assert.match(app, /const OPERATING_START_DATE = "2026-08-27"/, "รอบใช้งานจริงต้องเริ่มวันที่ 27 สิงหาคม 2026");
assert.match(app, /candidate < OPERATING_START_DATE \? OPERATING_START_DATE : candidate/, "ช่วงข้อมูลเริ่มต้นต้องไม่ย้อนก่อนวันเริ่มใช้งานจริง");
assert.match(app, /resultMetric\(exceptionsAvailable, sorted\.length\)[\s\S]+รายการรอตรวจ/, "การ์ดรายการรอตรวจต้องตรงกับรายการที่กรองแล้ว");
assert.match(app, /ขยายย้อนหลัง 90 วัน/, "หน้าไม่มีข้อมูลต้องแนะนำให้ขยายช่วงวัน");
assert.match(html, /หน้านี้ใช้ข้อมูลจริงจาก Supabase/, "หน้า login ต้องอธิบายสาเหตุที่ต้องเข้าสู่ระบบ");
assert.doesNotMatch(html, /gmail\.js/, "หน้าเว็บต้องไม่โหลดตัวอ่าน Gmail ที่เลิกใช้แล้ว");
assert.equal(existsSync(join(root, "gmail.js")), false, "ต้องลบ gmail.js ที่ไม่ได้ใช้แล้ว");
assert.equal(existsSync(join(root, "fx.js")), false, "ต้องลบ fx.js placeholder ที่ไม่ได้ใช้แล้ว");
assert.match(app, /const core = await Promise\.allSettled/, "ตัวโหลดภาพรวมต้องยอมให้ข้อมูลบางส่วนสำเร็จได้");
assert.match(app, /ตัวเลขส่วนนี้จะแสดง “—” แทนศูนย์/, "หน้าเว็บต้องไม่แสดงศูนย์ปลอมเมื่อข้อมูลจริง timeout");
assert.match(app, /const cloudQueryKey = \(\) =>/, "คลังไฟล์ต้องสร้าง cache key ตามตัวกรอง");
assert.match(app, /requestId !== cloudState\.requestId \|\| key !== cloudQueryKey\(\)/, "ผลค้นหาเก่าต้องเขียนทับตัวกรองใหม่ไม่ได้");
assert.match(app, /retryTransientFileRequest\(action, attempts = 3\)/, "Preview ต้องลองใหม่เมื่อ Storage หรือฐานข้อมูล timeout");
assert.match(app, /const exceptionsAvailable = liveOverviewState\.exceptionsReady/, "หน้า Exception ต้องแยกข้อมูลไม่พร้อมออกจากศูนย์จริง");
assert.match(app, /const operationsAvailable = Array\.isArray\(liveOverviewState\.operations\)/, "หน้ารายงานต้องแยกคิวไม่พร้อมออกจากไม่มีข้อมูล");
assert.match(app, /const logsAvailable = liveOverviewState\.logsReady/, "Audit Log ต้องไม่แสดงศูนย์เมื่อ query ล้มเหลว");
assert.match(app, /LIVE_COMPANY_CODES/, "ต้องแยก 9 บริษัทจริงออกจากแถวรวมชื่อระบบ");
assert.match(app, /\.filter\(isLiveCompanyRow\)/, "ผลคิวและผลกระทบยอดต้องกรองแถว PM\/SYS123\/XXX ออก");
assert.match(app, /ภาพรวมการกระทบยอด 3 จุด/, "หน้ารายวันต้องสรุป STM\/PM เทียบ BO ในจุดเดียว");
assert.match(app, /ขั้นถัดไปที่แนะนำ/, "หน้ารายวันต้องบอกงานถัดไปที่ผู้ตรวจควรทำ");
assert.match(app, /date === PROD_TODAY && !selectedQuality\.some/, "หน้ารายวันต้องเลื่อนไปวันที่ล่าสุดที่มีผลจริงเมื่อวันนี้ยังไม่มีผลรัน");
assert.match(app, /Audit Sheet · ภาพรวมทุกบริษัท/, "หน้ารายวันต้องมีตารางภาพรวมแบบสเปรดชีต");
assert.match(app, /data-sheet-mode="\$\{row\.missing\.length/, "แต่ละบริษัทต้องมีปุ่มไปแก้ไฟล์ ตรวจข้อผิดปกติ หรืออนุมัติ");
assert.match(app, /data-case-open=/, "ตาราง Exception ต้องมีปุ่มตรวจเคสที่เห็นชัด");
assert.match(app, /data-case-files=/, "ตาราง Exception ต้องมีปุ่มเปิดไฟล์ประกอบโดยตรง");
assert.match(app, /class="case-file-row"/, "ไฟล์ประกอบในเคสต้องแสดงเป็นรายการที่กด Preview ได้ทั้งแถว");
assert.ok(app.includes('data-file-status="${file.parse_error ? "error" : file.parsed ? "parsed" : "waiting"}"`'), "attribute สถานะไฟล์ต้องปิด quote ครบเพื่อไม่ให้ DOM ของรายการไฟล์เสีย");
assert.match(app, /Sb\.exceptionFiles\(e\.runId, e\.clarificationFileId\)/, "Drawer ต้องโหลดไฟล์ที่ใช้สร้าง recon run เฉพาะตอนเปิดเคส");
assert.match(app, /ไฟล์ประกอบของเคสนี้/, "Drawer ต้องมีส่วนไฟล์ประกอบที่เข้าใจง่าย");
assert.match(app, /ยอดตรงกัน หรือบันทึกความเสียหายแล้ว/, "เงื่อนไขปิดเคสต้องไม่วนกลับจนอนุมัติไม่ได้");
assert.match(app, /กำลังโหลดข้อมูลจริง…/, "หน้า Exception ต้องบอกผู้ใช้ชัดเจนระหว่างโหลดข้อมูลจริง");
assert.match(app, /recon-kpi-grid/, "สรุปผลกระทบยอดต้องใช้การ์ดหลักขนาดสม่ำเสมอ");
assert.match(app, /function safeExceptionDetail\(e\)/, "เคสย้อนหลังที่วันที่เสียต้องไม่แสดง undefined หรือ NaN ต่อผู้ใช้");

console.log("App shell QA follow-up: 30 checks passed");
