import fs from 'node:fs';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href);
const db=await PGlite.create();
await db.exec(`create role authenticated;create role anon;create schema auth;create schema storage;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('app.user',true),'')::uuid$$;
create function current_user_active() returns boolean language sql stable as $$select coalesce(current_setting('app.active',true),'true')='true'$$;
create function current_app_role() returns text language sql stable as $$select current_setting('app.role',true)$$;
create function has_company_access(c text) returns boolean language sql stable as $$select c=current_setting('app.company',true)$$;
create function can_attach_pending_pair_evidence(c uuid) returns boolean language sql stable as $$select current_setting('app.pending',true)='true'$$;
create table exceptions(id uuid primary key,company text,status text);
create table storage.objects(bucket_id text,name text,owner_id text,metadata jsonb);
create table case_evidence(id uuid primary key,exception_id uuid references exceptions(id),storage_path text unique,file_name text,size_bytes bigint,mime_type text,uploaded_by uuid,created_at timestamptz default now());
alter table case_evidence enable row level security;
grant usage on schema auth to authenticated;grant execute on all functions in schema auth to authenticated;`);
await db.exec(fs.readFileSync('supabase/20261009_register_case_evidence.sql','utf8'));
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const m={id:uid(3),exception_id:uid(2),storage_path:`case-evidence/${uid(2)}/${uid(1)}/${uid(3)}`,file_name:'3XB_EVIDENCE.docx',size_bytes:4,mime_type:'application/octet-stream',uploaded_by:uid(1)};
await db.query('insert into exceptions values ($1,\'FR8\',\'open\')',[uid(2)]);
await db.query('insert into storage.objects values(\'audit-files\',$1,$2,\'{"size":4}\')',[m.storage_path,uid(1)]);
const actor=async(role='lead',company='FR8',user=uid(1))=>{await db.exec('reset role');await db.query("select set_config('app.user',$1,false),set_config('app.role',$2,false),set_config('app.company',$3,false)",[user,role,company]);await db.exec('set role authenticated');};
const save=meta=>db.query('select (register_case_evidence($1::jsonb)).*',[JSON.stringify(meta)]);
await actor('lead','OTHER');await assert.rejects(save(m),/ไม่มีสิทธิ์บริษัท/);
await actor('lead','FR8',uid(9));await assert.rejects(save(m),/ไม่ถูกต้อง/);
await actor('viewer');await assert.rejects(save(m),/ไม่มีสิทธิ์แนบ/);
await actor('shift_lead');await assert.rejects(save(m),/ไม่มีสิทธิ์แนบ/);
await actor();await assert.rejects(save({...m,size_bytes:9}),/ขนาดในคลัง/);
assert.equal((await save(m)).rows[0].file_name,'3XB_EVIDENCE.docx','filename does not change company ownership');
assert.equal((await save(m)).rows[0].id,m.id,'same UUID retry returns original');
await assert.rejects(save({...m,file_name:'other.docx'}),/ไม่ตรง/);
await db.exec('reset role');await db.exec("update exceptions set status='closed'");await actor();
assert.equal((await save(m)).rows[0].id,m.id,'receipt retry after closure does not change case');
await assert.rejects(save({...m,id:uid(4),storage_path:`case-evidence/${uid(2)}/${uid(1)}/${uid(4)}`}),/ไม่มีสิทธิ์แนบ/);
await db.exec('reset role');await db.exec("update exceptions set status='clarifying'");await actor('shift_lead');
const next={...m,id:uid(4),storage_path:`case-evidence/${uid(2)}/${uid(1)}/${uid(4)}`};
await assert.rejects(save(next),/ขนาดในคลัง/);
await db.exec('reset role');await db.query('insert into storage.objects values(\'audit-files\',$1,$2,\'{"size":4}\')',[next.storage_path,uid(9)]);await actor();
await assert.rejects(save(next),/ขนาดในคลัง/,'another uploader owned the object');
await db.exec('reset role');await db.query('update storage.objects set owner_id=$1 where name=$2',[uid(1),next.storage_path]);await actor('shift_lead');
assert.equal((await save(next)).rows[0].id,next.id,'shift lead can attach to clarifying as in original policy');
await db.query("select set_config('app.active','false',false)");await assert.rejects(save(m),/ต้องเข้าสู่ระบบ/);
await db.exec('reset role');assert.equal((await db.query('select count(*)::int as n from case_evidence')).rows[0].n,2);
assert.equal((await db.query("select has_function_privilege('anon','register_case_evidence(jsonb)','EXECUTE') as allowed")).rows[0].allowed,false);
await db.exec("update exceptions set status=null");await actor();await db.query("select set_config('app.active','true',false)");
await assert.rejects(save({...m,id:uid(5),storage_path:`case-evidence/${uid(2)}/${uid(1)}/${uid(5)}`}),/ไม่มีสิทธิ์แนบ/);
await db.close();
console.log('PASS: actual migration on synthetic PostgreSQL: role/company/owner/size checks, same-ID recovery, no overwrite, closed/null status denial and no anonymous execution. Not a full live Supabase or concurrency test.');
