const assert = require('node:assert/strict');
const fs = require('node:fs'), vm = require('node:vm');
const ctx = vm.createContext({});
vm.runInContext(fs.readFileSync('audit-review.js','utf8') + '\nthis.review = AuditReview;', ctx);
const base={company:'UFABET7M',date:'2026-10-01',direction:'ฝาก',status:'answered'};
assert.equal(ctx.review.isWaiting(base),true);
for (const status of ['clarifying','closed','approved','damage','pair_pending']) assert.equal(ctx.review.isWaiting({...base,status,hasEvidence:true}),false);
assert.equal(ctx.review.isWaiting({...base,closureRequestId:'pending'}),false);
assert.equal(ctx.review.isWaiting({...base,manualPairId:'pending'}),false);
assert.equal(ctx.review.isWaiting({...base,status:'open',clarificationFileId:'file'}),true);
assert.equal(ctx.review.isWaiting({...base,status:'open',hasEvidence:true}),false);
const options={filters:{from:'2026-10-01',to:'2026-10-03',company:'ALL',direction:'ALL'},canAccessCompany:c=>c==='UFABET7M'};
assert.equal(ctx.review.rows([base,{...base,company:'3XB'},{...base,date:'2026-10-04'},{...base,closureRequestId:'x'}],options).length,1);
assert.equal(ctx.review.rows([base],{...options,filters:{...options.filters,direction:'ถอน'}}).length,0);
assert.equal(ctx.review.rows([base],{...options,filters:{...options.filters,company:'3XB'}}).length,0);
const app=fs.readFileSync('app.js','utf8');
assert.match(app,/id: "audit-review", label: "Audit รอตรวจ"/);
assert.match(app,/VIEWS\['audit-review'\]/);
assert.match(app,/data-action-route="audit-review"/);
assert.match(app,/btnClarify: "request_clarify"/);
assert.match(fs.readFileSync('index.html','utf8'),/audit-review\.js\?v=audit-review-20261006/);
console.log('Audit review queue: stage separation, linked sources, company access, date/direction filters and existing-case routing passed');
