const assert=require('node:assert/strict'),fs=require('node:fs');
const schema=require('../mc8-sheet-schema.js'),live=require('../mc8-live-sheets.js'),writer=require('../xlsx-writer.js');
assert.ok(fs.readFileSync(require.resolve('../mc8-live-sheets.js'),'utf8').includes('id="mc8-live-export"'));
assert.ok(fs.readFileSync(require.resolve('../app.js'),'utf8').includes('audit_reconciliation_workbook'));
const row=(overrides={})=>({key:'row',isPair:true,kind:'matched',company:'MC8',account:'AUTOPEER',direction:'deposit',code:'PAIR-1',bo:{user:'bo-user',reference:'BO-1',account:'1111',bank:'KBANK'},pm:{user:'pm-user',reference:'PM-1',account:'1111',bank:'KBANK'},boAmount:100,pmAmount:100,boTime:'2026-09-15 10:00:00',pmTime:'2026-09-15 10:00:10',reason:'same amount and identity',boSource:{row:2},pmSource:{row:2,timeColumn:'paymentTime',amountColumn:'realAmount'},...overrides});
const rows=[row(),row({key:'info',code:'PAIR-INFO',kind:'advisory',reason:'แสดงข้อมูลเพิ่มเติมโดยไม่ต้องยืนยัน'}),row({key:'review',code:'EX-1',isPair:false,kind:'review',boAmount:200,pmAmount:200,reason:'รอ Audit ยืนยัน'}),row({key:'error',code:'EX-2',isPair:false,kind:'review',account:'AZPAY',direction:'withdraw',boAmount:300,pmAmount:null,pm:{},reason:'ไม่พบ STM/PM'}),row({key:'crossday',code:'EX-XDAY',isPair:false,kind:'pending_next_day',account:'COREPAY',exType:'cross_day',reason:'รอข้อมูลของวันถัดไป'}),row({key:'closed',code:'EX-3',isPair:false,kind:'closed',account:'1998545397',boAmount:50,pmAmount:50,reason:'Audit ปิดเคสแล้ว'})];
const before=JSON.stringify(rows),sheets=live.buildAuditExportSheets(rows,'MC8','2026-09-15',true,schema);
assert.deepEqual(sheets.map(s=>s.name),['ข้อมูลทั้งหมด','สรุป','1998545397','AUTOPEER · ฝาก','AZPAY · ถอน','COREPAY · ฝาก']);
const all=sheets[0],summary=sheets[1],at=sheets.find(s=>s.name==='AUTOPEER · ฝาก');
assert.equal(all.title,undefined,'first header starts at row 1');
assert.equal(all.headers.at(-1),'สถานะสำหรับเทียบทีมกระทบมือ');
assert.ok(all.headers.indexOf('STM/PM · วัน / เวลา')<all.headers.indexOf('BO · วัน / เวลา'));
assert.deepEqual(all.rowTones,['','','error','error','warning','']);
for(const [i,tone] of [[0,'success'],[1,'success'],[4,'warning'],[5,'success']])assert.equal(all.cellTones[i].at(-1),tone);
for(const [header,value] of [['BO · ยอด',750],['STM/PM · ยอด',450],['ผลต่างยอด',-300]])assert.equal(all.footerRows[0][all.headers.indexOf(header)],value);
assert.equal(summary.footerRows[0][4],450);assert.equal(summary.footerRows[0][5],750);assert.equal(summary.footerRows[0][6],-300);
assert.equal(at.rows.length,3);
assert.deepEqual(at.rows.map(r=>r[all.headers.length-1]),['ปิดได้ทันที','แจ้งข้อมูล · ไม่ต้องยืนยัน','ปิดไม่ได้/ต้องตรวจ']);
assert.match(at.rows[0][at.headers.indexOf('เหตุผลระบบ')],/เวลา PM: paymentTime/);
assert.match(at.rows[0][at.headers.indexOf('เหตุผลระบบ')],/ยอด PM: realAmount/);
assert.equal(summary.rows.find(r=>r[1]==='AUTOPEER · ฝาก')[7],1,'advisory is not an Audit action');
assert.equal(sheets.find(s=>s.name==='1998545397').rows[0][all.headers.length-1],'ปิดเคสแล้ว');
assert.match(sheets.find(s=>s.name==='COREPAY · ฝาก').rows[0][all.headers.length-1],/ค้างรอข้อมูลข้ามวัน/);
assert.equal(sheets.find(s=>s.name==='AZPAY · ถอน').rowTones[0],'error');
// The provider-source column rules remain unchanged in the table adapter.
const legacyAt=live.tableView(rows.filter(r=>r.account==='AUTOPEER'),'MC8','2026-09-15',true,'AT ฝ',schema);
assert.deepEqual(legacyAt.headers.slice(0,schema.sheets.find(s=>s.name==='AT ฝ').headers.length),schema.sheets.find(s=>s.name==='AT ฝ').headers);
assert.equal(legacyAt.rows[0][legacyAt.headers.indexOf('requestTime')],'');
assert.equal(legacyAt.rows[0][legacyAt.headers.indexOf('paymentTime')],'2026-09-15 10:00:10');
const expired=live.tableView([row({pmSource:{row:3,timeColumn:'expiredTime',amountColumn:'realAmount'}})],'PS8','2026-09-15',true,'AT ฝ',schema);
assert.equal(expired.rows[0][expired.headers.indexOf('paymentTime')],'');
assert.equal(expired.rows[0][expired.headers.indexOf('expiredTime')],'2026-09-15 10:00:10');
for(const company of live.COMPANIES){
 const input=[row({key:'a',company,account:'ฝาก SCB ตาม BO 0123456789',boAccountLabel:'ฝาก SCB ตาม BO 0123456789',boTime:'2026-09-27 23:41:00',pmTime:'2026-09-27 23:40:00'}),row({key:'b',company,account:'ฝาก SCB ตาม BO 0123456789',boAccountLabel:'ฝาก SCB ตาม BO 0123456789',boTime:'2026-09-27 00:26:00',pmTime:'2026-09-27 00:25:00'}),row({key:'c',company,account:'CP2 PAYMENT ถอน 000000CP2',direction:'withdraw'})];
 const output=live.buildAuditExportSheets(input,company,'2026-09-27',true,schema),detail=output.slice(2);
 assert.equal(detail.length,2);assert.equal(detail.reduce((n,s)=>n+s.rows.length,0),input.length);
 assert.deepEqual(output[1].rows.map(r=>r[1]),live.accountReviewGroups(input).map(g=>g.label));
 const bank=detail.find(s=>s.name===output[1].rows.find(r=>r[1].includes('SCB'))[0]);
 assert.deepEqual(bank.rows.map(r=>r[bank.headers.indexOf('STM/PM · วัน / เวลา')]),['2026-09-27 00:25:00','2026-09-27 23:40:00']);
 assert.equal(bank.rows[0][bank.headers.indexOf('BO · วัน / เวลา')],'2026-09-27 00:26:00');
 assert.equal(output[1].footerRows[0][4],live.summarize(input).pmCents/100);
 assert.equal(output[1].footerRows[0][5],live.summarize(input).boCents/100);
}
const collisionRows=['ข้อมูลทั้งหมด','สรุป','รอ STM',"'บัญชี'",'A'.repeat(40)+'1','A'.repeat(40)+'2','a'.repeat(40)+'3','บัญชี:หนึ่ง','บัญชี/หนึ่ง'].map((account,i)=>row({key:'collision-'+i,account,boAccountLabel:account}));
const collision=live.buildAuditExportSheets(collisionRows,'MC8','2026-09-15',true,schema);
assert.equal(new Set(collision.map(s=>s.name.toLowerCase())).size,collision.length);
assert.ok(collision.every(s=>s.name.length<=31&&!/[\\/?*\[\]:]/.test(s.name)));
assert.deepEqual(collision[1].rows.map(r=>r[1]),live.accountReviewGroups(collisionRows).map(g=>g.label));
const orphan=row({key:'pm-only',account:'UNKNOWN',isPair:false,kind:'review',boAmount:null,bo:{},pmAmount:12});
const orphanExport=live.buildAuditExportSheets([rows[0],orphan],'MC8','2026-09-15',true,schema);
assert.equal(orphanExport.slice(2).reduce((n,s)=>n+s.rows.length,0),2,'PM-only rows must not be lost');
assert.ok(orphanExport[1].rows.some(r=>r[1].startsWith('STM/PM ไม่มี BO')));
assert.equal(JSON.stringify(rows),before,'export never changes amounts, identities or cases');
(async()=>{const blob=writer.build(sheets,'MC8 2026-09-15');assert.ok(blob.size>1000);const xml=new TextDecoder().decode(await blob.arrayBuffer());assert.ok(xml.includes('ข้อมูลทั้งหมด'));assert.ok(xml.includes('FFFCE4D6'));assert.ok(xml.includes('FFFFF2CC'));assert.ok(xml.includes('<row r="1" ht="26" customHeight="1">'));console.log('Account workbook export: all companies, unchanged amounts/matches, unique names, orphan retention, chronological rows and XLSX styles passed');})().catch(e=>{console.error(e);process.exitCode=1;});
