import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
assert.match(html,/<section[^>]*id="loginGate"[^>]*hidden>/);
assert.match(html,/<section[^>]*id="connectionGate"[^>]*aria-live="polite"[^>]*>/);
const nodes=new Map();
const $=selector=>{if(!nodes.has(selector))nodes.set(selector,{hidden:false,disabled:false,value:'unsaved audit note'});return nodes.get(selector);};
const context={$};
vm.runInNewContext(source.slice(source.indexOf('function showLoginGate('),source.indexOf('function render()')),context);
const draft=$('#responseText');
let calls=0,release;
context.showConnectingGate('timeout',()=>{calls++;return new Promise(resolve=>{release=resolve;});});
assert.equal($('#loginGate').hidden,true);
assert.equal($('#appShell').hidden,true,'Do not admit data before permissions are verified');
assert.equal($('#connectionGate').hidden,false);
assert.equal($('#accessCheckRetry').hidden,false);
const pending=$('#accessCheckRetry').onclick();
await $('#accessCheckRetry').onclick();
assert.equal(calls,1,'Retry is read-only and coalesced; no repeated refresh loop');
release();await pending;
assert.equal($('#accessCheckRetry').disabled,false);
assert.equal($('#responseText'),draft);
assert.equal(draft.value,'unsaved audit note');
context.showLoginGate('explicit access denial');
assert.equal($('#connectionGate').hidden,true);
assert.equal($('#loginGate').hidden,false);
assert.equal($('#loginError').textContent,'explicit access denial');
$('#newPassword').focus=()=>{};
context.showPasswordResetGate();
assert.equal($('#connectionGate').hidden,true);
assert.equal($('#resetForm').hidden,false);
assert.match(source,/\$\('#connectionGate'\)\.hidden = true;\n  \$\("#loginGate"\)\.hidden = true;\n  \$\("#appShell"\)\.hidden = false/);
console.log('Connecting gate: no login flash, no auth bypass, single retry and unchanged draft passed');
