const fs=require('node:fs'),assert=require('node:assert/strict'),vm=require('node:vm');
const app=fs.readFileSync('app.js','utf8');
const answer=app.slice(app.indexOf('$("#btnRespond").addEventListener'),app.indexOf('$("#btnDamage").addEventListener'));
assert.ok(answer.includes('$("#responseText").value.trim()'));
assert.ok(!answer.includes('$("#noteText").value'));
assert.ok(!answer.includes('|| e.responseText'),'Require a new explicit answer, do not silently resend old text');
assert.ok(answer.indexOf('await Sb.submitClarification')<answer.indexOf("recordCaseUiResult(e, 'ส่งคำชี้แจงสำเร็จ"));
assert.ok(answer.includes('if (e.status !== "clarifying") return'));
assert.ok(answer.includes('e.clarificationFileId'));
const closure=app.slice(app.indexOf('async function persistCaseClosure'),app.indexOf('async function completeQuickClose'));
assert.ok(closure.indexOf('await Sb.closeException')<closure.indexOf('recordCaseUiResult'));
const helper=app.slice(app.indexOf('const caseUiResults'),app.indexOf('async function persistCaseClosure'));
const ctx=vm.createContext({Sb:{currentEmail:()=> 'audit@example.test'},currentUser:()=>({username:'Audit'}),nowStamp:()=> 'sample-time'});
vm.runInContext(helper+'\nthis.record=recordCaseUiResult;this.key=caseUiKey;this.results=caseUiResults;',ctx);
const first={id:'EX1',company:'AT4',date:'2026-10-01',runId:'run1',status:'open'};
ctx.record(first,'บันทึก Note แล้ว');
assert.equal(ctx.results.get(ctx.key(first)).status,'open');
assert.notEqual(ctx.key(first),ctx.key({...first,company:'UR9'}));
assert.notEqual(ctx.key(first),ctx.key({...first,date:'2026-10-02'}));
assert.notEqual(ctx.key(first),ctx.key({...first,runId:'run2'}));
assert.ok(app.includes('lastUiResult?.status===e.status'));
for(const id of ['responseText','btnGoMissing','caseChecklistSection'])assert.ok(app.includes(`id="${id}"`));
console.log('Workflow clarity: separate answer, verified save results, cross-case isolation and original evidence/status guards passed');
