import assert from 'node:assert/strict';
import fs from 'node:fs';
const sql = fs.readFileSync(new URL('../supabase/20260906_scoped_daily_checklist.sql', import.meta.url), 'utf8');
const migration = fs.readFileSync(new URL('../supabase/20260930_current_checklist_exception_counts.sql', import.meta.url), 'utf8');
const ex = sql.slice(sql.indexOf('), ex as ('), sql.indexOf('), base as ('));
assert.match(ex, /cross join lateral/);
assert.match(ex, /from public\.exceptions\s+where run_id=j\.last_run_id/);
assert.match(ex, /superseded_by_exception_id is null/);
assert.match(ex, /code not like '%-C%'/);
assert.match(ex, /j\.business_date between p_from and p_to and not j\.is_archived/);
assert.match(ex, /upper\(j\.company\)=p_company/);
assert.match(sql, /security invoker/);
assert.doesNotMatch(sql, /security definer|disable row level security/i);
assert.match(migration, /pg_get_functiondef/);
assert.match(migration, /superseded_by_exception_id is null/);
assert.match(migration, /code not like ''%-C%''/);
assert.match(migration, /raise exception 'audit_daily_checklist definition is not the expected version'/);
console.log('Checklist current-lifecycle aggregate and RLS preservation checks passed');
