import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const source = fs.readFileSync(new URL('../supabase.js', import.meta.url), 'utf8');
const start = source.indexOf('async function requestClarification(');
const end = source.indexOf('async function closeException(', start);
const calls = [];
let response = [{status:'clarifying'}];
let evidence = [];
const ctx = { json: async (...args) => { if (args[0].startsWith('/rest/v1/case_evidence?')) return evidence; calls.push(args); return response; } };
vm.createContext(ctx);
vm.runInContext(source.slice(start,end), ctx);
await ctx.requestClarification('case-id','open',{requested_by:'test-user'});
assert.ok(calls[0][0].includes('status=eq.open'));
assert.equal(calls[0][1].headers.Prefer,'return=representation');
assert.equal(JSON.parse(calls[0][1].body).status,'clarifying');
response=[];
await assert.rejects(()=>ctx.requestClarification('case-id','answered',{}));
response=[{status:'open'}];
await assert.rejects(()=>ctx.requestClarification('case-id','open',{}));
const count=calls.length;
await assert.rejects(()=>ctx.requestClarification('case-id','closed',{}));
assert.equal(calls.length,count,'closed case cannot be reopened by clarification');
console.log('Clarification save: verified response, concurrent status guard, denied/no-row rejection');
const before = calls.length;
await assert.rejects(()=>ctx.submitClarification('case-id',{response_text:'คำตอบ'}));
await assert.rejects(()=>ctx.submitClarification('case-id',{response_text:' ',clarification_file_id:'file-id'}));
assert.equal(calls.length,before,'incomplete evidence/answer never sent');
const answer = {response_text:'ตรวจหลักฐานแล้ว',clarification_file_id:'file-id'};
response=[];
await assert.rejects(()=>ctx.submitClarification('case-id',answer));
response=[{status:'answered'}];
await ctx.submitClarification('case-id',answer);
assert.ok(calls.at(-1)[0].includes('status=eq.clarifying'));
assert.equal(JSON.parse(calls.at(-1)[1].body).status,'answered');
const uploadCalls=[];
ctx.signedIn=()=>true;
ctx.authUser=()=>({id:'user-1'});
ctx.crypto={randomUUID:()=> 'upload-1'};
ctx.cfg=()=>({bucket:'audit-files'});
ctx.req=async (...args)=>{uploadCalls.push(args);};
ctx.post=async (_table,rows)=>rows;
const file={name:'evidence.pdf',size:4,type:'application/pdf',arrayBuffer:async()=>new ArrayBuffer(4)};
const saved=await ctx.uploadCaseEvidence('case-1',file);
assert.equal(saved.exception_id,'case-1');
assert.equal(uploadCalls[0][1].headers['x-upsert'],'false');
await assert.rejects(()=>ctx.uploadCaseEvidence('case-1',{...file,size:20971521}));
assert.equal(uploadCalls.length,1);
ctx.post=async()=>{throw Error('timeout');};
evidence=[{id:'upload-1',exception_id:'case-1'}];
assert.equal((await ctx.uploadCaseEvidence('case-1',file)).id,'upload-1','read back uncertain metadata commit');
evidence=[];
await assert.rejects(()=>ctx.uploadCaseEvidence('case-1',file),/ยังยืนยันการผูกเคสไม่ได้/);
assert.ok(uploadCalls.every(([,options])=>options.method==='POST'),'never delete uncertain upload');
assert.equal(calls.at(-1)[1].headers.Prefer,'return=representation');
evidence=[{id:'persisted-evidence'}];
await ctx.submitClarification('case-id',{response_text:'ตอบพร้อมไฟล์แนบใหม่'});
assert.equal(JSON.parse(calls.at(-1)[1].body).status,'answered');
