import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const context=vm.createContext({});
vm.runInContext(read('../damage-summary.js')+';this.D=DamageSummary;',context);
const D=context.D;
const row=(id,company,code,shift)=>({id,company,employee:'นาย A',employeeCode:code,shift,amount:5000,cause:'[damage:v2:employee] confirmed',collectionReady:true,collection:{approved_amount:'5000.00',paid_amount:'2000.00'}});
const a=row('a','MC8','A001','X1'), b=row('b','MC8','A002','X3'), c=row('c','3XB','A001','X1');
assert.notEqual(D.employeeKey(a),D.employeeKey(b));
assert.notEqual(D.employeeKey(a),D.employeeKey(c));
assert.equal(D.groupBy([a,b,c],'employee').length,3);
assert.match(D.identityLabel(a),/นาย A · X1 · MC8 · A001/);
assert.equal(D.employeeLabel({...a,employee:'changed later',collection:{category:'employee',party_name:'original approved',shift:'X1'}}),'original approved');
assert.equal(D.shiftLabel({...a,shift:'X5',collection:{category:'employee',party_name:'original approved',shift:'X1'}}),'X1');
assert.equal(D.collectionTotals(a).net,3000);
assert.equal(D.collectionTotals({...a,collectionReady:false}).net,null);
assert.equal(D.collectionTotals({...a,collection:null}).net,null);
assert.equal(D.collectionTotals({...a,collection:{approved_amount:5000,paid_amount:6000}}).net,null);
assert.equal(D.collectionTotals({...a,collection:{approved_amount:5000,paid_amount:null}}).net,null);
const unknown1={...a,id:'u1',employeeCode:''},unknown2={...a,id:'u2',employeeCode:''};
assert.equal(D.groupBy([unknown1,unknown2],'employee').length,2,'missing IDs must not merge by name');
const summary=D.groupBy([a,{...a,id:'other',collection:null}],'shift')[0];
assert.equal(summary.netGroups.find(g=>g.category==='employee').net,3000);
assert.equal(summary.netGroups.find(g=>g.category==='employee').paid,2000);
assert.equal(summary.netGroups.find(g=>g.category==='employee').pending,1);
const sql=read('../supabase/20261003_damage_collections.sql');
for(const contract of ['for update','security definer','public.current_user_active()',"('lead','admin')",'public.has_company_access(c.company)',"f.company=c.company",'unique(company,transfer_reference)','source_file_id uuid not null unique','paid+p_amount>c.approved_amount','voided_at is null','r.source_file_id=p_source_file_id','d.shift','other.party_name<>btrim(p_party_name)','revoke all on public.damage_collections','grant select on public.damage_collections','from public,anon']) assert.ok(sql.includes(contract),contract);
assert.ok(!/update public\.damages|update public\.exceptions|delete from/i.test(sql),'install and receipts never change case or gross damages');
const app=read('../app.js');
assert.match(app,/DamageSummary\.employeeKey\(d\) === liveDamageState.employee/);
assert.match(app,/collectionIdentityChecked/);
assert.match(app,/receiptChecked/);
assert.match(app,/requestId=crypto.randomUUID/);
assert.match(app,/liveDamageState.collectionError\?'—'/);
const source=read('../supabase.js');
const ledgerCode=source.slice(source.indexOf('  async function damageCollections('),source.indexOf('  async function approveDamageCollection('));
let ledgerCalls=[];
const ledgerRead=new Function('json',ledgerCode+';return damageCollections;')(async url=>{
  ledgerCalls.push(url);const q=new URL(url,'https://test.invalid').searchParams;
  const rows=url.includes('damage_receipts')?Array.from({length:123},(_,id)=>({id,paid_at:'2026-11-01',amount:1})):[];
  return rows.slice(Number(q.get('offset')),Number(q.get('offset'))+50);
});
assert.equal((await ledgerRead(['test-id'])).receipts.length,123,'do not truncate payments at server page cap');
assert.ok(ledgerCalls.every(url=>url.includes('damage_id=in.') && !url.includes('paid_at=')),'later-month receipts must stay attached to original damage');
const code=source.slice(source.indexOf('  async function approveDamageCollection('),source.indexOf('  async function evidenceFiles('));
let result=[{damage_id:'d',id:'receipt'}];
const api=new Function('rpc',code+';return {approveDamageCollection,confirmDamageReceipt};')(async()=>result);
await api.approveDamageCollection({p_damage_id:'d'});
await api.confirmDamageReceipt({p_damage_id:'d',p_id:'receipt'});
result=[{damage_id:'other',id:'receipt'}];
await assert.rejects(api.confirmDamageReceipt({p_damage_id:'d',p_id:'receipt'}));
console.log('Damage collections: separate identity, unknown totals, receipt validation and SQL security contracts pass. Not a live database execution.');
