import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context=vm.createContext({});
vm.runInContext(fs.readFileSync(new URL('../damage-summary.js',import.meta.url),'utf8')+';globalThis.D=DamageSummary;',context);
const D=context.D;
assert.equal(D.classify('เจ้าของบัญชีโกง').category,'unclassified');
assert.equal(D.classify('ระบบ ATP เกิดปัญหา').category,'unclassified');
const cause=D.encode('employee','X1','ตรวจหลักฐานแล้ว');
assert.equal(D.classify(cause).subcategory,'X1');
assert.equal(D.classify(cause).detail,'ตรวจหลักฐานแล้ว');
assert.throws(()=>D.encode('system','X1','note'));
assert.throws(()=>D.encode('employee','',''));
assert.throws(()=>D.encode('','X1','note'));
assert.equal(D.classify('[damage:v1:system:X1] invalid').category,'unclassified');
for(const category of ['employee','backoffice','external','pm','game']) {
  const encoded=D.encodeDetails(category,'หลักฐานยืนยัน');
  assert.equal(D.classify(encoded).category,category);
  assert.equal(D.classify(encoded).detail,'หลักฐานยืนยัน');
}
assert.throws(()=>D.encodeDetails('system','legacy must stay legacy'));
assert.throws(()=>D.encodeDetails('employee',' '));
assert.equal(D.shiftLabel({cause}), 'รอยืนยันกะ');
assert.equal(D.shiftLabel({shift:'X8'}),'X8');
assert.equal(D.employeeLabel({employee:'ไม่ระบุ'}),'รอยืนยันผู้เกี่ยวข้อง');
assert.equal(D.monthRange('2026-09').from,'2026-09-15');
assert.equal(D.monthRange('2026-10').to,'2026-10-31');
assert.equal(D.monthRange('2028-02').to,'2028-02-29');
assert.throws(()=>D.monthRange('2026-08'));
assert.throws(()=>D.monthRange('2026-13'));
for(const value of ['',null,undefined,'bad','1.001',-1]) assert.equal(D.cents(value),null);
assert.equal(D.cents(0),0);
assert.equal(D.cents('34.15'),3415);
assert.equal(D.financeComplete('รอปิดรอบ'),false);
assert.equal(D.financeComplete('ยังไม่เสร็จ'),false);
assert.equal(D.financeComplete('ปิดรอบแล้ว'),true);
assert.equal(D.financeComplete('closed'),true);
const rows=[{id:'1',amount:100.10,cause},{id:'2',amount:35.20,cause:D.encode('system','','PM')},{id:'3',amount:10,cause:'old'}];
assert.equal(D.summarize(rows).total,145.30);
assert.equal(D.summarize([...rows,rows[0]]).total,145.30);
assert.equal(D.summarize([...rows,rows[0]]).issues.length,1);
assert.equal(D.summarize([{id:'missing',amount:null}]).issues.length,1);
const grouped=D.groupBy([{id:'a',shift:'X1',employee:'A',amount:500,cause:D.encodeDetails('employee','test')},{id:'b',shift:'X1',employee:'B',amount:1000,cause:D.encodeDetails('pm','test')},{id:'c',shift:'X5',amount:25,cause:'old'}],'shift');
assert.equal(grouped[0].total,1500);
assert.equal(grouped[0].groups.find(g=>g.category==='employee').amount,500);
assert.equal(grouped[0].groups.find(g=>g.category==='pm').amount,1000);
const app=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
assert.match(app,/damageConfirmedAmount/);
assert.match(app,/hrStatus: "ยังไม่ส่งบุคคล"/);
assert.match(app,/damageExportLive/);
console.log('Damage categories: explicit classification, exact totals, missing data and duplicate guards passed');
