const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={Sb:{signedIn:()=>true},state:{role:'lead',dataset:'production'},money:String};
vm.createContext(context);vm.runInContext(fs.readFileSync('case-closure.js','utf8')+'\nthis.api=CaseClosure;',context);
assert.equal(context.api.approvalNote('approve',''),'');
assert.equal(context.api.approvalNote('approve','รับทราบ'),'รับทราบ');
assert.throws(()=>context.api.approvalNote('reject',''));
assert.throws(()=>context.api.approvalNote('approve','a'.repeat(2001)));
const q={outcome:'no_loss',snapshot:{system_amount:88,bank_amount:87.93}};
assert.equal(context.api.selfEligible(q),true);
for(const changed of [{outcome:'damage'},{snapshot:{system_amount:null,bank_amount:0}},{snapshot:{system_amount:88,bank_amount:82.99}},{snapshot:{system_amount:'NaN',bank_amount:88}}])assert.equal(context.api.selfEligible({...q,...changed}),false);
const sql=fs.readFileSync('supabase/20261005_document_closure_workflow.sql','utf8');
for(const text of ['enable row level security','document_days between 1 and 365','old.document_due_at','case_has_stored_document','storage.objects','case_closure_one_pending','ต้นทางเปลี่ยนหลังส่งคำขอ','now()<e.document_due_at','case_closure_submit','requested_by=auth.uid()'])assert.ok(sql.includes(text),text);
assert.ok(sql.indexOf("if q.outcome='damage' then")<sql.indexOf('insert into public.damages'));
assert.match(sql,/new\.document_due_at:=old\.document_due_at/);
assert.match(sql,/p_outcome='no_loss' and not has_document/);
assert.match(sql,/p_action='reject'.*<10/);
assert.doesNotMatch(sql,/update public\.exceptions set (?:system_amount|bank_amount|risk_amount)/);
const app=fs.readFileSync('app.js','utf8'),sb=fs.readFileSync('supabase.js','utf8');
assert.match(app,/return !e\.closureRequestId && Boolean/);
assert.match(app,/if \(state\.dataset === 'production'\) return CaseClosure\.openSubmit\(e\)/);
assert.match(sb,/"case_closure_request_id", "document_due_at"/);
console.log('Document closure: optional approval reason, self limits, role/evidence/SLA/snapshot guards and separated queues passed');
