import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source = fs.readFileSync(new URL('../evidence-recommendations.js', import.meta.url),'utf8');
const context = vm.createContext({});
vm.runInContext(source+';this.cards=EvidenceRecommendations.cards;',context);
const row={business_date:'2026-09-14',company:'EXAMPLE',payer_company:'TEST',provider:'<script>alert(1)</script>',amount:100,evidence_note:'<img src=x onerror=alert(1)>',source_file_id:'test'};
const output=context.cards([row]);
assert.ok(output.includes('รอ Audit ยืนยัน'));
assert.ok(output.includes('ยังไม่ยืนยันคู่ธุรกรรม'));
assert.ok(!output.includes('<script>'));
assert.ok(!output.includes('<img'));
assert.ok(context.cards([]).includes('ยังไม่มีคู่แนะนำ'));
assert.ok(context.cards(Array(501).fill(row)).includes('500 รายการแรก'));
assert.doesNotMatch(source,/manualMatchClarificationFile|confirmDamage/);
const sql=fs.readFileSync(new URL('../supabase/20260916_evidence_recommendations.sql',import.meta.url),'utf8');
assert.match(sql,/enable row level security/);
assert.match(sql,/created_by = auth.uid\(\)/);
assert.match(sql,/has_company_access\(company\) and public.has_company_access\(payer_company\)/);
assert.match(sql,/evidence_recommendations.company,evidence_recommendations.payer_company/);
assert.doesNotMatch(sql,/update public.exceptions|insert into public.damages|grant.*update/i);
console.log('Evidence recommendation safety tests passed');
let modalHtml='';
const readerContext=vm.createContext({openModal:(_title,html)=>{modalHtml=html;},document:{getElementById:()=>({querySelectorAll:()=>[]})}});
vm.runInContext(source+';this.show=EvidenceRecommendations.showCaseLinks;',readerContext);
readerContext.show([{recommendation_id:'r1',reason:'Reason <unsafe>',evidence_recommendations:{...row,id:'r1'}}],{},()=>{});
assert.ok(modalHtml.includes('recommendation-route'));
assert.ok(modalHtml.includes('บริษัทเจ้าของรายการ'));
assert.ok(modalHtml.includes('บริษัทจ่ายแทน'));
assert.ok(modalHtml.includes('Reason &lt;unsafe&gt;'));
assert.ok(modalHtml.includes('<details class="recommendation-full">'));
assert.ok(!modalHtml.includes('<details open'));
console.log('Recommendation reader: structured summary, escaped reason, collapsed full note passed');
vm.runInContext('this.group=EvidenceRecommendations.groupCasesHtml;',readerContext);
const rec={id:'shared',company:'A',payer_company:'B',business_date:'2026-09-14'};
const linked=(id,company,status,date='2026-09-14')=>({recommendation_id:'shared',exception_id:id,exceptions:{id,code:'EX-'+id,company,status,business_date:date}});
const group=readerContext.group(rec,[linked('1','A','open'),linked('2','B','closed'),linked('2','B','closed'),linked('3','C','open'),linked('4','B','open','2026-09-13')],['1']);
assert.ok(group.includes('รอ Audit ตรวจ'));
assert.ok(group.includes('ปิดเคสแล้ว'));
assert.equal((group.match(/data-related-case="2"/g)||[]).length,1);
assert.ok(!group.includes('EX-3')&&!group.includes('EX-4'));
assert.ok(readerContext.group(rec,[linked('1','A','open')],[]).includes('ไม่ได้หมายความว่าตรวจครบ'));
console.log('Cross-company group: deduplicated cases, separate statuses, scoped dates and missing-side warning passed');
