import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../evidence-recommendations.js',import.meta.url),'utf8');
const context=vm.createContext({});
vm.runInContext(source+';this.match=EvidenceRecommendations.forCase;',context);
const e={id:'case-one',run_id:'latest-run',company:'AA',business_date:'2026-09-14',status:'open',system_amount:100};
const link={exception_id:e.id,exceptions:{...e},evidence_recommendations:{company:'AA',payer_company:'BB',business_date:e.business_date,status:'pending_audit'}};
const check=(row,links,run='latest-run')=>context.match(row,links,run).length;
assert.equal(check({case:e},[link]),1);
assert.equal(check({case:{...e,id:'same-amount-other-case'}},[link]),0);
assert.equal(check({pair:{amount:100}},[link]),0);
assert.equal(check({case:e},[link],'old-run'),0);
assert.equal(check({case:e},[{...link,exceptions:{...e,run_id:'old-run'}}]),0);
assert.equal(check({case:{...e,company:'CC'}},[link]),0);
assert.equal(check({case:{...e,business_date:'2026-09-15'}},[link]),0);
for(const status of ['closed','approved','damage'])assert.equal(check({case:{...e,status}},[link]),0);
assert.equal(check({case:e},[{...link,evidence_recommendations:{...link.evidence_recommendations,status:'rejected'}}]),0);
assert.equal(check({case:e},[]),0);
assert.equal(check({case:e},[{exception_id:e.id}]),0);
const before=JSON.stringify(e);check({case:e},[link]);assert.equal(JSON.stringify(e),before);
const css=fs.readFileSync(new URL('../evidence-recommendations.css',import.meta.url),'utf8');
assert.match(css,/has-evidence-recommendation:nth-child\(even\)/);
assert.match(css,/has-evidence-recommendation:hover/);
assert.match(css,/focus-visible/);
const sql=fs.readFileSync(new URL('../supabase/20260916_evidence_recommendation_cases.sql',import.meta.url),'utf8');
assert.match(sql,/last_run_id=e.run_id/);
assert.match(sql,/grant select on/);
assert.doesNotMatch(sql,/update public.exceptions|insert into public.damages|grant (insert|update|all)/i);
console.log('Evidence highlight: exact UUID, current run, date/company scope, no amount-only matches, closed cases excluded, accessible styling passed');
