import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const app=fs.readFileSync('app.js','utf8');
const api=fs.readFileSync('supabase.js','utf8');
const sql=fs.readFileSync('supabase/20261009_head_selected_case_file.sql','utf8');
const calls=[];
const ctx=vm.createContext({json:async url=>{calls.push(url);return [];},rpc:(name,args)=>({name,args})});
vm.runInContext(api.slice(api.indexOf('  async function evidenceFiles('),api.indexOf('  async function auditLogs(')),ctx);
await ctx.evidenceFiles({company:'FR8',from:'2026-10-07',to:'2026-10-08'});
assert.ok(calls[0].includes('kind=eq.doc_clarify'));
await ctx.evidenceFiles({company:'3XB',from:'2026-10-07',to:'2026-10-07',includeSourceFiles:true});
assert.ok(!calls[1].includes('kind=eq.doc_clarify'));
assert.ok(calls[1].includes('mail_batches.company=eq.3XB'));
assert.ok(calls[1].includes('business_date=gte.2026-10-07'));
assert.ok(calls[1].includes('business_date=lte.2026-10-07'));
for(const s of ["headClose.id='btnHeadClose'","['lead','admin'].includes(state.role)&&can('approve')&&!closed",'CaseClosure.openSubmit(e)',"canAccessCompany(fileCompany)",'Sb.linkSelectedCaseFile(e.dbId,b.dataset.linkMail,note)'])assert.ok(app.includes(s),s);
for(const s of ["not in ('lead','admin')",'public.has_company_access(e.company)','public.has_company_access(file_company)','j.last_run_id=e.run_id','e.superseded_by_exception_id is not null','e.manual_pair_id is not null','e.case_closure_request_id is not null','ไม่เขียนทับหลักฐาน',"bucket_id='audit-files'",'evidence_link_only'])assert.ok(sql.includes(s),s);
assert.ok(!sql.includes("set status"));
assert.ok(!sql.includes('system_amount ='));
console.log('Head file selection: scoped dates/company, role guards and evidence-only SQL contract passed');
