import fs from 'node:fs';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const {PGlite}=await import(pathToFileURL(process.argv[2]).href),db=await PGlite.create();
await db.exec(`create role anon;create role authenticated;
create function has_company_access(c text) returns boolean language sql as $$select c='FR8'$$;
create table exceptions(id uuid primary key,company text,business_date date,run_id uuid,superseded_by_exception_id uuid,account text,direction text,currency text,ex_type text,system_amount numeric,bank_amount numeric,bo_raw text,stm_raw text,customer_details jsonb default '{}');
create table daily_recon_jobs(company text,business_date date,is_archived boolean,status text,last_run_id uuid);
create table recon_runs(id uuid primary key,summary jsonb,file_ids uuid[]);
create table source_files(id uuid primary key,company text,file_name text,parsed boolean,parse_error text,kind text,storage_path text);
create schema storage;create table storage.objects(name text,bucket_id text);create table case_evidence(id uuid,exception_id uuid,storage_path text,size_bytes bigint);`);
const old=fs.readFileSync('supabase/20261004_manual_amount_difference.sql','utf8');await db.exec(old.slice(old.indexOf('create or replace function public.validate_manual_pair'),old.indexOf('create or replace function public.submit_manual_case_pair')));
await db.exec(fs.readFileSync('supabase/20261009_manual_pair_scoped_readiness.sql','utf8'));
const uid=n=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,run=uid(1),bo=uid(2),stm=uid(3),f1=uid(4),f2=uid(5);
const entry=name=>({company:'FR8',identity:'CYBERPLUS',direction:'deposit',rows:2,source_files:[name]});
const summary={source_parser_completion:true,bo_first:{complete:false,required:[entry('BO.xlsx')],received:[entry('PM.xlsx')],missing:[{identity:'OTHER'}]}};
await db.query('insert into recon_runs values($1,$2,$3)',[run,summary,[f1,f2]]);
await db.query("insert into daily_recon_jobs values('FR8','2026-10-08',false,'needs_review',$1)",[run]);
await db.query("insert into source_files values($1,'FR8','BO.xlsx',true,null,'bo_main','bo-path'),($2,'FR8','PM.xlsx',true,null,'pm_statement','pm-path')",[f1,f2]);
await db.exec("insert into storage.objects values('bo-path','audit-files'),('pm-path','audit-files')");
await db.query("insert into exceptions(id,company,business_date,run_id,account,direction,currency,ex_type,system_amount,bank_amount,bo_raw,stm_raw) values($1,'FR8','2026-10-08',$3,'CYBERPLUS','ฝาก','THB','missing_stm',200,null,'real BO',null),($2,'FR8','2026-10-08',$3,'CYBERPLUS','ฝาก','THB','missing_bo',null,200,null,'real PM')",[bo,stm,run]);
await db.query('update exceptions set customer_details=$1',[{source_rows:{bo:{fileId:f1,row:1},stm:{fileId:f2,row:1}}}]);
const validate=()=>db.query("select validate_manual_pair($1,$2,'same',null) as proof",[bo,stm]);
assert.equal((await validate()).rows[0].proof.difference,0,'complete selected pair allowed while unrelated source missing');
assert.equal((await db.query("select summary->'bo_first'->>'complete' as complete from recon_runs")).rows[0].complete,'false','day remains incomplete');
await db.exec("delete from storage.objects where name='pm-path'");await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.exec("insert into storage.objects values('pm-path','audit-files')");
await db.query('update exceptions set customer_details=$1 where id=$2',[{},stm]);await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.query('update exceptions set customer_details=$1 where id=$2',[{source_rows:{bo:{fileId:f1,row:1},stm:{fileId:f2,row:1}}},stm]);
await db.exec("update daily_recon_jobs set status='running'");await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.exec("update daily_recon_jobs set status='needs_review';update source_files set parsed=false where file_name='PM.xlsx'");await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.exec("update source_files set parsed=true;update exceptions set account='OTHER' where ex_type='missing_bo'");await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.exec("update exceptions set account='CYBERPLUS';update exceptions set direction='ถอน' where ex_type='missing_bo'");await assert.rejects(validate(),/ทิศทาง/);
await db.exec("update exceptions set direction='ฝาก';update exceptions set bank_amount=206 where ex_type='missing_bo'");await assert.rejects(validate(),/5 บาท/);
await db.exec("update exceptions set bank_amount=200 where ex_type='missing_bo'");await db.query('update daily_recon_jobs set last_run_id=$1',[uid(9)]);await assert.rejects(validate(),/คู่ที่เลือกยังไม่พร้อม/);
await db.query('update daily_recon_jobs set last_run_id=$1',[run]);await db.exec("update exceptions set stm_raw='ไม่พบ' where ex_type='missing_bo'");await assert.rejects(validate(),/ต้นทาง/);
assert.equal((await db.query("select has_function_privilege('authenticated','manual_pair_scoped_source_ready(uuid,text)','execute') as allowed")).rows[0].allowed,false);
await db.close();console.log('PASS: actual scoped migration permits complete pair only; incomplete day retained, running/stale/unparsed/missing-account/source/direction/amount blocked. Synthetic PostgreSQL.');
