const assert=require('node:assert/strict');
const fs=require('node:fs');
const {rowsOf,filter,mount,providerOf,sheetOf,summarize,summaries,COMPANIES,SHEETS}=require('../mc8-live-sheets.js');
const input={run:{id:'r1',matched:1,stm_count:999,bo_count:999,jobStatus:'needs_review',summary:{match_evidence:[{account:'AUTOPEER',direction:'withdraw',amount:355,stmAmount:355,boAmount:355,bo:{fileId:'bo',date:'2026-09-16',sec:3600,row:2},stm:{fileId:'pm',date:'2026-09-16',sec:3700,row:9},customer:{bo:{reference:'ref'},stm:{reference:'ref'}}}]}},complete:true,cases:[{id:'case1',code:'EX-1',account:'COREPAY',direction:'ฝาก',status:'open',system_amount:150,bank_amount:null,company:'MC8',business_date:'2026-09-16',bo_date:'2026-09-17',bo_raw:'bo-cross-day-1',ex_type:'cross_day'},{id:'case1-warning',code:'EX-2',account:'COREPAY',direction:'ฝาก',status:'open',system_amount:150,bank_amount:null,company:'MC8',business_date:'2026-09-16',bo_date:'2026-09-17',bo_raw:'bo-cross-day-1',ex_type:'large_amount'}]};
const before=JSON.stringify(input), rows=rowsOf(input);
assert.equal(rows.length,3);assert.equal(rows[0].boTime,'2026-09-16 01:00:00');
assert.equal(rows[1].pmAmount,null);assert.equal(rows[1].kind,'review');
assert.equal(filter(rows,'COREPAY','deposit','review').length,2);
assert.equal(filter(rows,'AUTOPEER','deposit','all').length,0);
assert.equal(providerOf('ATP / Autopeer'),'AT');assert.equal(providerOf('CPXM'),'CP');assert.equal(providerOf('M24'),'M');
assert.equal(sheetOf(rows[0]),'AT ถ');assert.deepEqual(COMPANIES,['3XB','MC8','MR9','PS8','UR9']);assert.equal(SHEETS.length,8);
const totals=summarize(rows);assert.equal(totals.pmCount,1);assert.equal(totals.pmCents,35500);assert.equal(totals.boCount,2);assert.equal(totals.boCents,50500);assert.equal(totals.crossDayCount,1);assert.equal(totals.crossDayBoCents,15000);assert.equal(totals.diffBeforeCents,0);assert.equal(totals.diffAfterCents,-15000);
assert.equal(summaries(rows)['CP ฝ'].boCount,1,'warning cases sharing one BO transaction must be deduplicated');
const overlap=rowsOf({run:{summary:{match_evidence:[{account:'AUTOPEER',direction:'withdraw',boAmount:25,stmAmount:25,bo:{date:'2026-09-16'},stm:{date:'2026-09-16'},customer:{bo:{reference:'same-bo'},stm:{reference:'same-pm'}}}]}},cases:[{id:'warning',account:'AUTOPEER',direction:'ถอน',system_amount:25,bank_amount:25,bo_date:'2026-09-16',stm_date:'2026-09-16',bo_raw:'same raw bo',stm_raw:'same raw pm',customer_details:{bo:{reference:'same-bo'},stm:{reference:'same-pm'}},ex_type:'large_amount'}]});
const overlapTotals=summarize(overlap);assert.equal(overlapTotals.pmCount,1);assert.equal(overlapTotals.boCount,1);assert.equal(overlapTotals.unmatchedPmCount,0);assert.equal(overlapTotals.unmatchedBoCount,0);
assert.equal(JSON.stringify(input),before);
const src=fs.readFileSync(require.resolve('../mc8-live-sheets.js'),'utf8');
assert.ok(!/\.rpc\(|\.post\(|\.patch\(|\.saveRun\(|\.confirmAuditPairs\(/.test(src));
const nodes=new Map();const container={innerHTML:'',querySelector(s){if(!nodes.has(s))nodes.set(s,{});return nodes.get(s);},querySelectorAll(){return [];}};
mount(container,{signedIn:()=>false,date:'2026-09-16',onLocal(){},load(){throw Error('should never load');}});
assert.ok(container.innerHTML.includes('กรุณาเข้าสู่ระบบจริง'));
mount(container,{signedIn:()=>true,date:'2026-09-16',company:'MR9',companies:COMPANIES,onLocal(){},load:async(company,date)=>{assert.equal(company,'MR9');assert.equal(date,'2026-09-16');return input;}});
setImmediate(()=>{assert.ok(container.innerHTML.includes('EX-1'));assert.ok(container.innerHTML.includes('355.00'));assert.ok(container.innerHTML.includes('สรุปยอดแยกทุกหน้า'));assert.ok(container.innerHTML.includes('ผลต่างหลังรวมข้ามวัน'));assert.ok(!container.innerHTML.includes('ผลหรือหลักฐานยังไม่ครบ'));assert.ok(container.innerHTML.includes('ปิดได้ทันที'));console.log('Audit live sheets: five-company read-only adapter, deduplicated totals, cross-day totals and login guard passed');});
