const assert=require('node:assert/strict');
const fs=require('node:fs');
const schema=require('../mc8-sheet-schema.js');
delete globalThis.MC8SheetSchema;
const {rowsOf,filter,filterAndSortEntries,columnMatch,mount,providerOf,sheetOf,summarize,summaries,tableView,providerFooter,pmAmountHeader,buildAuditExportSheets,COMPANIES,SHEETS}=require('../mc8-live-sheets.js');
assert.equal(providerOf('พร้อมเพย์-ANT-AU(anypay)(QR)'), 'ANT');
assert.equal(providerOf('anypay'), 'ANT');
assert.equal(providerOf('CHANT'), 'OTHER');
for (const company of ['3XB','MC8','MR9','PS8','UR9']) {
  const antRows=['deposit','withdraw'].map((direction,i)=>({key:`ANT-${i}`,company,account:'พร้อมเพย์-ANT-AU(anypay)(QR)',direction,kind:'review',boAmount:200+i*100,boTime:'2026-10-03 12:00:00',bo:{user:'xb-user'}}));
  assert.equal(sheetOf(antRows[0]), 'ANT ฝ');
  assert.equal(sheetOf(antRows[1]), 'ANT ถ');
  const sheets=buildAuditExportSheets(antRows,company,'2026-10-03',true,schema);
  const details=sheets.slice(2);
  assert.equal(details.length,2,`${company} splits PM by direction`);
  assert.deepEqual(details.flatMap(sheet=>sheet.rows.map(r=>r[sheet.headers.indexOf('BO · ยอด')])),[200,300]);
  assert.deepEqual(details.flatMap(sheet=>sheet.rows.map(r=>r[sheet.headers.indexOf('ประเภท')])),['ฝาก','ถอน']);
}
assert.ok(!buildAuditExportSheets([],'FR8','2026-10-03',true,schema).some(s=>s.name.startsWith('ANT ')));
const input={run:{id:'r1',matched:1,stm_count:999,bo_count:999,jobStatus:'needs_review',summary:{match_evidence:[{account:'AUTOPEER',direction:'withdraw',amount:355,stmAmount:355,boAmount:355,bo:{fileId:'bo',date:'2026-09-16',sec:3600,row:2},stm:{fileId:'pm',date:'2026-09-16',sec:3700,row:9},customer:{bo:{reference:'ref'},stm:{reference:'ref'}}}]}},complete:true,cases:[{id:'case1',code:'EX-1',account:'COREPAY',direction:'ฝาก',status:'open',system_amount:150,bank_amount:null,company:'MC8',business_date:'2026-09-16',bo_date:'2026-09-17',bo_raw:'bo-cross-day-1',ex_type:'cross_day'},{id:'case1-warning',code:'EX-2',account:'COREPAY',direction:'ฝาก',status:'open',system_amount:150,bank_amount:null,company:'MC8',business_date:'2026-09-16',bo_date:'2026-09-17',bo_raw:'bo-cross-day-1',ex_type:'large_amount'}]};
const before=JSON.stringify(input), rows=rowsOf(input);
assert.equal(rows.length,2);assert.equal(rows[0].boTime,'2026-09-16 01:00:00');
assert.equal(rows[1].pmAmount,null);assert.equal(rows[1].kind,'review');
assert.equal(filter(rows,'COREPAY','deposit','review').length,1);
assert.equal(filter(rows,'AUTOPEER','deposit','all').length,0);
assert.equal(providerOf('ATP / Autopeer'),'AT');assert.equal(providerOf('CPXM'),'CP');assert.equal(providerOf('M24'),'M');assert.equal(providerOf('LOCALPAY'),'LP');
assert.equal(sheetOf(rows[0]),'AT ถ');assert.deepEqual(COMPANIES,['3XB','MC8','MR9','PS8','UR9','AT4','FR8','SK8','UFABET7M']);assert.ok(SHEETS.includes('CY ฝ'));assert.ok(SHEETS.includes('LO ถ'));
const totals=summarize(rows);assert.equal(totals.pmCount,1);assert.equal(totals.pmCents,35500);assert.equal(totals.boCount,2);assert.equal(totals.boCents,50500);assert.equal(totals.crossDayCount,1);assert.equal(totals.crossDayBoCents,15000);assert.equal(totals.diffBeforeCents,0);assert.equal(totals.diffAfterCents,-15000);
assert.equal(summaries(rows)['CP ฝ'].boCount,1,'warning cases sharing one BO transaction must be deduplicated');
const overlap=rowsOf({run:{summary:{match_evidence:[{account:'AUTOPEER',direction:'withdraw',boAmount:25,stmAmount:25,bo:{date:'2026-09-16'},stm:{date:'2026-09-16'},customer:{bo:{reference:'same-bo'},stm:{reference:'same-pm'}}}]}},cases:[{id:'warning',company:'MC8',account:'AUTOPEER',direction:'ถอน',system_amount:25,bank_amount:25,bo_date:'2026-09-16',stm_date:'2026-09-16',bo_raw:'same raw bo',stm_raw:'same raw pm',customer_details:{bo:{reference:'same-bo'},stm:{reference:'same-pm'}},ex_type:'large_amount'}]},'MC8');
const overlapTotals=summarize(overlap);assert.equal(overlapTotals.pmCount,1);assert.equal(overlapTotals.boCount,1);assert.equal(overlapTotals.unmatchedPmCount,0);assert.equal(overlapTotals.unmatchedBoCount,0);
assert.equal(overlap.length,1,'large_amount advisory must not be exported as an Audit action row');
const stalePair={account:'MYPAY',company:'PS8',direction:'deposit',boAmount:900,stmAmount:900,bo:{date:'2026-09-19',sec:36000},stm:{date:'2026-09-19',sec:36000},customer:{bo:{reference:'BO-900'},stm:{bank:'SCB',name:'CUSTOMER'}}};
const staleRows=rowsOf({run:{summary:{match_evidence:[stalePair]}},cases:[
  {id:'old-bo',company:'PS8',account:'MYPAY',direction:'ฝาก',ex_type:'missing_stm',system_amount:900,bo_date:'2026-09-19',bo_time:'10:00:00',customer_details:{bo:{reference:'BO-900'}}},
  {id:'old-stm',company:'PS8',account:'MYPAY',direction:'ฝาก',ex_type:'missing_bo',bank_amount:900,stm_date:'2026-09-19',stm_time:'10:00:00',customer_details:{stm:{bank:'SCB',name:'CUSTOMER'}}},
]},'PS8');
assert.equal(staleRows.length,3,'workbook must retain open persisted cases until backend closes them');
assert.equal(staleRows[0].isPair,true);
const xbIdView=tableView(rowsOf({run:{summary:{match_evidence:[{company:'MC8',account:'AUTOPEER',direction:'withdraw',boAmount:2200,stmAmount:2200,bo:{date:'2026-09-16',sec:80000},stm:{date:'2026-09-16',sec:100,timeColumn:'updateTime',amountColumn:'transferredAmount'},customer:{bo:{reference:'2718608',note:'Sapan: 6aaac4bfed5cd6e1fd9d67a6'},stm:{reference:'P2C-20260916-233303-UIHHCL',transactionReference:'P2C-20260916-233303-UIHHCL',sourceId:'P2C-20260916-233303-UIHHCL',providerReference:'6aaac4bfed5cd6e1fd9d67a6'}}}] }},cases:[]},'MC8'),'MC8','2026-09-16',true,'AT ถ',schema);
assert.equal(xbIdView.rows[0][xbIdView.headers.indexOf('id')],'P2C-20260916-233303-UIHHCL','XB AT column A id must show P2C');
assert.equal(xbIdView.rows[0][xbIdView.headers.indexOf('_id')],'6aaac4bfed5cd6e1fd9d67a6','XB AT _id must show provider 6aa id');
for(const [account,sheet] of [['AZPAY','AZ ถ'],['COREPAY','CP ถ'],['MYPAY','M ถ'],['LOCALPAY','LP ถ']]){
  const providerRows=rowsOf({run:{summary:{match_evidence:[{company:'3XB',account,direction:'withdraw',amount:100,bo:{date:'2026-09-16',sec:100},stm:{date:'2026-09-16',sec:110},method:'legacy-rule',customer:{bo:{reference:'BO-1'},stm:{sourceId:`${account}-1`,providerReference:'6aaac4bfed5cd6e1fd9d67a6'}}}] }},cases:[]},'3XB');
  const view=tableView(providerRows,'3XB','2026-09-16',true,sheet,schema);
  assert.equal(view.rows[0][view.headers.indexOf('_id')],'6aaac4bfed5cd6e1fd9d67a6',`${account} must display its own PM _id`);
  assert.equal(view.rows[0][view.headers.indexOf('หมายเหตุ')],'',`${account} BO note must stay blank when BO has no Sapan note`);
  assert.match(view.rows[0][view.headers.indexOf('เงื่อนไขที่จับคู่')],/legacy-rule/,`${account} matcher label belongs only in the condition column`);
}
const legacySapanRows=rowsOf({run:{summary:{match_evidence:[]}},cases:[{id:'legacy-sapan',company:'3XB',account:'AUTOPEER',direction:'ถอน',status:'open',system_amount:1300,bank_amount:1300,bo_date:'2026-09-15',stm_date:'2026-09-15',bo_raw:'1049603 | sapan: 6aa8a28b6f7ddd65ebf16ce8 | โอนจริง 1300 สำเร็จ 1265.99 คืน 34.01',customer_details:{bo:{note:'sapan: 6aa8a28b6f7ddd65ebf16ce8 | โอนจริง 1300 สำเร็จ 1265.99 คืน 34.01'},stm:{providerReference:'6aa8a28b6f7ddd65ebf16ce8'}}}]},'3XB');
assert.equal(legacySapanRows[0].bo.note,'6aa8a28b6f7ddd65ebf16ce8','legacy BO note must display only the Sapan provider id');
assert.equal(legacySapanRows[0].bo.providerReference,'6aa8a28b6f7ddd65ebf16ce8','legacy BO provider reference must be recovered from raw note');
const recoveredPmIdRows=rowsOf({run:{summary:{match_evidence:[]}},cases:[{id:'legacy-pm-id',company:'3XB',account:'AUTOPEER',direction:'ถอน',status:'open',system_amount:1300,bank_amount:1300,bo_raw:'1049603 | Spean: 6aa8a28b6f7ddd65ebf16ce8 | โอนจริง 1300 สำเร็จ 1265.99 คืน 34.01',stm_raw:'P2C-20260915-214651-AOJGPS | 1300 | autopeer | SUCCESSED | 6aa8a28b6f7ddd65ebf16ce8',customer_details:{bo:{note:'Spean: 6aa8a28b6f7ddd65ebf16ce8 | โอนจริง 1300 สำเร็จ 1265.99 คืน 34.01'},stm:{}}}]},'3XB');
const recoveredPmIdView=tableView(recoveredPmIdRows,'3XB','2026-09-15',true,'AT ถ',schema);
assert.equal(recoveredPmIdView.rows[0][recoveredPmIdView.headers.indexOf('_id')],'6aa8a28b6f7ddd65ebf16ce8','historical case must recover PM _id from its raw row');
assert.equal(recoveredPmIdView.rows[0][recoveredPmIdView.headers.indexOf('id')],'P2C-20260915-214651-AOJGPS','historical case must retain P2C in id and keep it separate from _id');
const fallbackPmIdRows=rowsOf({run:{summary:{match_evidence:[]}},cases:[{id:'missing-pm-id',company:'3XB',account:'AUTOPEER',direction:'ถอน',status:'open',system_amount:-100,bank_amount:100,bo_raw:'10495821 | Sapan: 6aa95f3e6f7ddd65ebf18744 | โอนจริง 100 สำเร็จ 100',stm_raw:'P2C-20260915-213500-TEST03 | 100 | autopeer',customer_details:{bo:{reference:'10495821',note:'Sapan: 6aa95f3e6f7ddd65ebf18744 | โอนจริง 100 สำเร็จ 100'},stm:{transactionId:'10495821'}}}]},'3XB');
const fallbackPmIdView=tableView(fallbackPmIdRows,'3XB','2026-09-15',true,'AT ถ',schema);
assert.equal(fallbackPmIdView.rows[0][fallbackPmIdView.headers.indexOf('_id')],'6aa95f3e6f7ddd65ebf18744','screen must show BO Sapan id when PM extractor left _id blank');
const legacySapanAll=buildAuditExportSheets(legacySapanRows,'3XB','2026-09-15',true,schema).find(sheet=>sheet.name==='ข้อมูลทั้งหมด');
assert.equal(legacySapanAll.rows[0][legacySapanAll.headers.indexOf('BO · รายละเอียดต้นฉบับ')],'6aa8a28b6f7ddd65ebf16ce8','export must not include payout/refund suffix after Sapan id');
const realAmountRows=rowsOf({run:{summary:{match_evidence:[{company:'MC8',account:'AUTOPEER',direction:'deposit',boAmount:200,stmAmount:250,bo:{date:'2026-09-16',sec:3600},stm:{date:'2026-09-16',sec:3600,timeColumn:'paymentTime',amountColumn:'realAmount'},customer:{bo:{reference:'BO-REAL'},stm:{reference:'PM-REAL'}}}]}},cases:[]},'MC8');
const realAmountView=tableView(realAmountRows,'MC8','2026-09-16',true,'AT ฝ',schema);
assert.equal(pmAmountHeader(realAmountView.headers,'AT ฝ'),'realAmount','XB deposit must total the actual realAmount column');
const realAmountFooter=providerFooter(realAmountView.headers,realAmountView.rows,'AT ฝ');
assert.ok(realAmountFooter.includes('ผลรวม realAmount'),'screen footer must identify the realAmount total');
assert.ok(realAmountFooter.includes('250.00'),'screen footer must total realAmount');
assert.ok(realAmountFooter.includes('200.00'),'screen footer must total BO for comparison');
assert.ok(realAmountFooter.includes('50.00'),'screen footer must show realAmount minus BO');
const allView=tableView(realAmountRows,'MC8','2026-09-16',true,'all',schema);
const allFooter=providerFooter(allView.headers,allView.rows,'all');
assert.ok(allFooter.includes('250.00')&&allFooter.includes('200.00')&&allFooter.includes('50.00'),'all-data screen must show STM/PM, BO and difference totals');
const realAmountExport=buildAuditExportSheets(realAmountRows,'MC8','2026-09-16',true,schema).find(sheet=>sheet.name==='AUTOPEER · ฝาก');
assert.equal(realAmountExport.footerRows[0][realAmountExport.headers.indexOf('STM/PM · ยอด')],250,'Excel footer must total realAmount');
assert.equal(realAmountExport.footerRows[0][realAmountExport.headers.indexOf('BO · ยอด')],200,'Excel footer must total BO');
assert.equal(realAmountExport.footerRows[0][realAmountExport.headers.indexOf('ผลต่างยอด')],50,'Excel footer must compare realAmount with BO');
const statementRow=(company,account,bank,direction)=>({key:`${company}-${account}-${direction}`,isPair:true,kind:'matched',company,account,direction,pm:{bank,name:'ผู้ถือบัญชี'},bo:{},pmAmount:100,boAmount:100,pmTime:'2026-09-28 01:00:00',boTime:'2026-09-28 01:00:00'});
const sheetNames=(company,statementRows)=>buildAuditExportSheets(statementRows,company,'2026-09-28',true,schema).map(sheet=>sheet.name);
const sys123Names=sheetNames('FR8',[statementRow('FR8','4311918665','SCB','deposit'),statementRow('FR8','4311918665','SCB','withdraw')]);
assert.equal(sys123Names.filter(name=>name.startsWith('4311918665')).length,2,'123 banks split deposit and withdrawal');
const sevenMBankNames=sheetNames('UFABET7M',[statementRow('UFABET7M','5034633891','SCB','deposit'),statementRow('UFABET7M','5034633891','SCB','withdraw')]);
assert.equal(sevenMBankNames.filter(name=>name==='5034633891').length,1,'7M uses BO identity once');
const sevenMTmnNames=sheetNames('UFABET7M',[statementRow('UFABET7M','0999999999','TMN','deposit'),statementRow('UFABET7M','0999999999','TMN','withdraw')]);
assert.equal(sevenMTmnNames.filter(name=>name.startsWith('0999999999')).length,2,'7M TMN splits deposit and withdrawal');
const xbNames=sheetNames('UR9',[statementRow('UR9','0123456789','SCB','deposit'),statementRow('UR9','0123456789','SCB','withdraw')]);
assert.equal(xbNames.filter(name=>name==='0123456789').length,1,'XB uses BO identity once');
assert.equal(JSON.stringify(input),before);
assert.equal(columnMatch('ปิดได้ทันที','ปิดได้'),true);
assert.equal(columnMatch('MC8',{values:['MC8','PS8']}),true);
assert.equal(columnMatch('UR9',{values:['MC8','PS8']}),false);
assert.deepEqual(filterAndSortEntries([
  {source:{id:'b'},values:['MC8',200]},
  {source:{id:'a'},values:['PS8',100]},
],{0:'8'},{index:1,direction:'asc'}).map(entry=>entry.source.id),['a','b'],'column filters and numeric sort must compose without mutating source data');
const src=fs.readFileSync(require.resolve('../mc8-live-sheets.js'),'utf8');
assert.ok(!/\.rpc\(|\.post\(|\.patch\(|\.saveRun\(|\.confirmAuditPairs\(/.test(src));
assert.ok(src.includes('mc8-live-fullscreen'),'workbook must expose a full-screen table control');
assert.ok(src.includes('data-live-filter-menu'),'workbook must expose an Excel-like value menu in each visible column header');
assert.ok(src.includes('เรียงน้อย → มาก'),'column menu must sort ascending like Excel');
assert.ok(src.includes('data-live-filter-value'),'column menu must list distinct values with checkboxes');
assert.ok(src.includes('data-live-column'),'workbook must expose hide/show controls for individual columns');
assert.ok(src.includes("liveCase?.id"),'real-case buttons must validate and forward the persisted exception UUID');
assert.ok(src.includes("await opts.onCase(liveCase,company)"),'real-case buttons must await the detail loader instead of silently navigating by display code');
assert.ok(src.includes('onCaseError'),'real-case buttons must surface load or permission failures');
assert.ok(!src.includes('entries.slice(page*50'),'live workbook must keep every filtered row in one scrollable table');
assert.ok(src.includes('แสดงครบ ${shown.length}'),'screen must explain that all filtered rows are shown on one page');
assert.ok(src.includes('id="mc8-live-wrap-text"'),'workbook must expose a show-all-text control');
assert.ok(src.includes('data-live-text-cell'),'long cells must be individually expandable');
assert.ok(src.includes('ช่อง “หมายเหตุ/โน้ต” อ่านจากช่องหมายเหตุในไฟล์ BO ต้นทาง'),'screen must explain BO note provenance');
assert.ok(!src.includes("'โน้ต':boNote||bo.reference||row.reason||''"),'empty BO notes must not be replaced by reference or system reason');
const nodes=new Map();const container={innerHTML:'',querySelector(s){if(!nodes.has(s))nodes.set(s,{});return nodes.get(s);},querySelectorAll(){return [];}};
mount(container,{signedIn:()=>false,date:'2026-09-16',onLocal(){},load(){throw Error('should never load');}});
assert.ok(container.innerHTML.includes('กรุณาเข้าสู่ระบบจริง'));
mount(container,{signedIn:()=>true,date:'2026-09-16',company:'MR9',companies:COMPANIES,onLocal(){},load:async(company,date)=>{assert.equal(company,'MR9');assert.equal(date,'2026-09-16');return input;}});
setImmediate(()=>{assert.ok(container.innerHTML.includes('COREPAY'));assert.ok(container.innerHTML.includes('355.00'));assert.ok(container.innerHTML.includes('สรุปยอดแยกตามบัญชี BO'));assert.ok(container.innerHTML.includes('ต่างหลังข้ามวัน'));assert.ok(!container.innerHTML.includes('โหลดผลหรือหลักฐานคู่ไม่ครบ'));assert.ok(container.innerHTML.includes('ปิดได้ทันที'));console.log('Audit live sheets: five-company read-only adapter, deduplicated totals, cross-day totals and login guard passed');});
