import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const app = fs.readFileSync(new URL('../app.js', import.meta.url), 'utf8');
const start = app.indexOf('function buildReviewExportSheets()');
const end = app.indexOf('/* ตัวสร้างชุดข้อมูลแต่ละชีต', start);
const rows = [['a', 'ฝาก'], ['b', 'ถอน'], ['c', 'PM']];
const ctx = { SHEET_BUILDERS: { exceptions: { build: () => ({ headers: ['เคส', 'ทิศทาง'], rows, title: 'ตรวจ', widths: [10, 10] }) } } };
vm.createContext(ctx);
vm.runInContext(app.slice(start, end) + ';globalThis.output = buildReviewExportSheets()', ctx);
assert.deepEqual(Array.from(ctx.output, x => x.name), ['ฝาก (ฝ)', 'ถอน (ถ)', 'รอระบุประเภท', 'รวม']);
assert.deepEqual(Array.from(ctx.output, x => x.rows.length), [1, 1, 1, 3]);
assert.equal(ctx.output[0].rows[0][0], 'a');
assert.equal(ctx.output[1].rows[0][0], 'b');
assert.equal(rows.length, 3);
rows.splice(1);
vm.runInContext('globalThis.output = buildReviewExportSheets()', ctx);
assert.deepEqual(Array.from(ctx.output, x => x.rows.length), [1, 0, 1]);
console.log('Review export: separate directions, unknown retained, scope preserved');
const customerStart = app.indexOf('function reviewCustomer(e, side)');
const customerEnd = app.indexOf('function reviewCustomerHtml', customerStart);
vm.runInContext(app.slice(customerStart, customerEnd), ctx);
ctx.example = { customerDetails: { bo: { account: '0012345678', name: '<ชื่อ>', user: 'member', reference: 'ref' } } };
vm.runInContext('globalThis.customer = reviewCustomer(example, "bo")', ctx);
assert.equal(ctx.customer.account, '0012345678');
assert.equal(ctx.customer.tail, '5678');
vm.runInContext('globalThis.customer = reviewCustomer({account:"9999999999"}, "stm")', ctx);
assert.equal(ctx.customer.account, '', 'never substitute company bank account for customer');
ctx.example.customerDetails.bo.account = 'xxx5678';
vm.runInContext('globalThis.customer = reviewCustomer(example, "bo")', ctx);
assert.equal(ctx.customer.tail, '', 'masked account must not become verified tail');
