const assert=require('node:assert/strict');
const {sheetRow,sheetHeaders,auditLabel}=require('../review-overview.js');
const pair={pair:{amount:100,stmAmount:100,bo:{date:'2026-09-08',sec:180},stm:{date:'2026-09-08',sec:240},customer:{bo:{user:'demo-user'},stm:{last4:'1234',bank:'GSB'}},timeDifferenceSeconds:60},account:'SCB-company',direction:'deposit'};
assert.equal(sheetRow(pair).length,sheetHeaders.length);
assert.equal(auditLabel(pair),'ยังไม่ยืนยันโดย Audit');
assert.equal(sheetRow(pair)[10],'User: demo-user');
assert.equal(sheetRow(pair)[9],''); // Customer bank must not copy company bank.
assert.equal(sheetRow({...pair,direction:'unknown'})[4],'ไม่ระบุประเภท');
assert.equal(auditLabel({case:{status:'answered'}}),'รอตรวจคำตอบ');
assert.equal(auditLabel({...pair,confirmation:{confirmed_at:'2026-09-09'}}),'Audit ยืนยันแล้ว');
console.log('Sheet fields and independent audit states passed');
const {normalizeHidden}=require('../review-overview.js');
require('node:assert/strict').deepEqual(normalizeHidden([0,1,2,2,26,27,-1,'5',null]),[2,26]);
require('node:assert/strict').deepEqual(normalizeHidden(null),[]);
const {filterColumns,columnValue}=require('../review-overview.js');
const make=(amount,sec,bank='GSB')=>({...pair,pair:{...pair.pair,amount,stmAmount:amount,bo:{date:'2026-09-08',sec},customer:{bo:{user:'demo-user'},stm:{bank,last4:'0012'}}}});
const items=[make(100,300),make(20,60,'SCB'),make(0,120)];
assert.deepEqual(filterColumns(items).map(r=>r.pair.amount),[20,0,100]);
assert.deepEqual(filterColumns(items,{}, {column:6,direction:'asc'}).map(r=>r.pair.amount),[0,20,100]);
assert.equal(filterColumns(items,{6:{op:'gte',value:'20'},18:{op:'equals',value:'gsb'}}).length,1);
assert.equal(filterColumns(items,{9:{op:'blank'}}).length,3);
assert.equal(filterColumns(items,{6:{op:'blank'}}).length,0);
assert.equal(filterColumns(items,{17:{op:'equals',value:'0012'}}).length,3);
assert.equal(columnValue(items[0],23),60);
const many=Array.from({length:110},(_,i)=>make(i,i*60));
assert.equal(filterColumns(many,{6:{op:'gte',value:'100'}}).length,10);
assert.equal(many[0].pair.amount,0); // Source rows must not be sorted in place.
const unknown={...pair,pair:{...pair.pair,bo:{},stm:{}}};
assert.equal(filterColumns([unknown,...items],{}, {column:5,direction:'desc'}).at(-1),unknown);
assert.equal(filterColumns(items,{5:{op:'gte',value:'2026-09-08 00:03'}}).length,1);
console.log('Column filters: combined, blank, leading zero, numeric, full data and chronological order passed');
